/** German copy for brand scopes corrected after the main translation pass. */
export const DE_BRAND_CORRECTIONS: Record<string, string> = {
  "Practical support when life becomes complicated":
    "Praktische Hilfe, wenn das Leben kompliziert wird",
  "BeistandPlus is a guided-support platform for people and families dealing with difficult practical tasks in Germany. It brings relocation and everyday administration together with bereavement support: understanding funeral choices and likely costs, recording wishes, organising documents, comparing suitable funeral providers and finding relevant funeral-cost policies or other funding and support routes through approved partners.":
    "BeistandPlus ist eine begleitete Unterstützungsplattform für Menschen und Familien mit schwierigen praktischen Aufgaben in Deutschland. Sie verbindet Umzugs- und Alltagsverwaltung mit Hilfe im Trauerfall: Bestattungsmöglichkeiten und voraussichtliche Kosten verstehen, Wünsche festhalten, Unterlagen ordnen, geeignete Bestattungsanbieter vergleichen und über zugelassene Partner passende Sterbegeldversicherungen oder andere Finanzierungs- und Unterstützungswege finden.",
  "German employers, community organisations and service partners supporting international staff and families, plus the large recurring need for guided bereavement, funeral-cost and life-administration support.":
    "Deutsche Arbeitgeber, Gemeinschaftsorganisationen und Dienstleistungspartner, die internationale Mitarbeitende und Familien unterstützen, sowie der wiederkehrende Bedarf an begleiteter Hilfe bei Trauerfällen, Bestattungskosten und Alltagsverwaltung.",
  "Employers, insurers, care and community organisations buying support for staff, members or families. The people receiving relocation, administration or bereavement help use the included service without a second BeistandPlus platform fee.":
    "Arbeitgeber, Versicherer, Pflege- und Gemeinschaftsorganisationen kaufen Unterstützung für Mitarbeitende, Mitglieder oder Familien. Die Menschen, die Umzugs-, Verwaltungs- oder Trauerfallhilfe erhalten, nutzen den enthaltenen Service ohne zweite BeistandPlus-Plattformgebühr.",
  "Important life administration is fragmented across public offices, insurers, employers, funeral providers and paper documents. During relocation or bereavement, people often do not know what must be done, what a funeral may cost, whether a policy or public support applies, or which provider is suitable. BeistandPlus gives them one guided route and a clear record.":
    "Wichtige Lebensverwaltung ist auf Behörden, Versicherer, Arbeitgeber, Bestattungsanbieter und Papierunterlagen verteilt. Bei einem Umzug oder Trauerfall wissen Menschen häufig nicht, was erledigt werden muss, was eine Bestattung kosten kann, ob eine Versicherung oder öffentliche Hilfe greift oder welcher Anbieter geeignet ist. BeistandPlus bietet einen begleiteten Weg und eine klare Akte.",
  "One guided case with a named support route, plain-language tasks, secure documents and approved specialist partners. The platform can help a family understand funeral options and costs, compare suitable providers, check whether an existing funeral-cost policy may apply and identify possible support routes. BeistandPlus coordinates and explains; regulated insurance advice, policy sales and legal decisions remain with authorised partners.":
    "Ein begleiteter Fall mit klarer Unterstützung, verständlichen Aufgaben, sicheren Unterlagen und zugelassenen Fachpartnern. Die Plattform hilft Familien, Bestattungsmöglichkeiten und Kosten zu verstehen, geeignete Anbieter zu vergleichen, eine mögliche bestehende Sterbegeldversicherung zu prüfen und Unterstützungswege zu erkennen. BeistandPlus koordiniert und erklärt; regulierte Versicherungsberatung, Versicherungsverkauf und Rechtsentscheidungen bleiben autorisierten Partnern vorbehalten.",
  "Families currently contact funeral providers, insurers, employers, public offices, charities and legal advisers separately. Relocation and bereavement administration is managed through phone calls, paper files and disconnected websites, leaving no single trusted case record.":
    "Familien wenden sich heute getrennt an Bestattungsanbieter, Versicherer, Arbeitgeber, Behörden, Wohlfahrtsorganisationen und Rechtsberater. Umzugs- und Trauerfallverwaltung läuft über Telefonate, Papierakten und getrennte Websites, sodass eine gemeinsame verlässliche Fallakte fehlt.",
  "People and families in Germany facing relocation, bereavement or complex life administration, reached through employers, insurers, care providers and community organisations.":
    "Menschen und Familien in Deutschland bei Umzug, Trauerfall oder komplexer Alltagsverwaltung, erreicht über Arbeitgeber, Versicherer, Pflegeanbieter und Gemeinschaftsorganisationen.",
  "BeistandPlus is funded by organisation subscriptions or support packages. Families are not charged a second platform fee, and any regulated policy or professional service is provided under a separate transparent agreement with an authorised partner.":
    "BeistandPlus wird durch Organisationsabos oder Unterstützungspakete finanziert. Familien zahlen keine zweite Plattformgebühr; regulierte Versicherungs- oder Fachleistungen werden in einem getrennten transparenten Vertrag mit einem autorisierten Partner erbracht.",

  "Clearer signals. Better-controlled decisions.":
    "Klarere Signale. Besser kontrollierte Entscheidungen.",
  "TraderOS is a subscription trading-signals and market-analysis SaaS/app for self-directed traders. It brings live market data from licensed sources, charts, technical indicators, AI-assisted signal explanations, alerts, risk levels, entry zones, stop-loss and take-profit planning, a trading journal and performance analysis into one system across forex, indices, commodities and crypto.":
    "TraderOS ist eine abonnierte Trading-Signal- und Marktanalyse-Software für selbstentscheidende Trader. Sie bündelt Live-Marktdaten aus lizenzierten Quellen, Charts, technische Indikatoren, KI-gestützte Signalerklärungen, Warnungen, Risikostufen, Einstiegsbereiche, Stop-Loss- und Take-Profit-Planung, Trading-Tagebuch und Leistungsanalyse für Devisen, Indizes, Rohstoffe und Kryptowährungen.",
  "Self-directed traders in the UK first, followed by selected international markets where the required market-data, financial-promotion and product rules have been completed.":
    "Zunächst selbstentscheidende Trader im Vereinigten Königreich, danach ausgewählte internationale Märkte, sobald die Anforderungen an Marktdaten, Finanzwerbung und Produktregeln erfüllt sind.",
  "Self-directed individual traders who want one transparent system for market monitoring, signal research, risk planning, alerts and performance review.":
    "Selbstentscheidende private Trader, die ein transparentes System für Marktbeobachtung, Signalprüfung, Risikoplanung, Warnungen und Leistungsanalyse wünschen.",
  "Retail traders currently combine charting tools, broker screens, social channels and opaque signal groups. They often cannot see why a signal appeared, how it performed historically or whether losses are being hidden. TraderOS makes the signal logic, risk and track record visible in one place.":
    "Private Trader kombinieren heute Chartprogramme, Brokeroberflächen, soziale Kanäle und undurchsichtige Signalgruppen. Häufig ist nicht erkennbar, warum ein Signal entstand, wie es historisch abschnitt oder ob Verluste verborgen werden. TraderOS macht Signallogik, Risiko und Erfolgsbilanz an einem Ort sichtbar.",
  "One subscription for clearly explained, timestamped market signals and disciplined risk tools. Each signal shows the market evidence behind it, possible entry area, invalidation level, stop-loss, take-profit scenarios and historical performance. TraderOS does not promise profit, hold client funds or present a forecast as certainty; the trader remains in control of every decision.":
    "Ein Abo für verständlich erklärte, zeitgestempelte Marktsignale und disziplinierte Risikowerkzeuge. Jedes Signal zeigt die Marktdaten dahinter, einen möglichen Einstiegsbereich, das Ungültigkeitsniveau, Stop-Loss, Take-Profit-Szenarien und historische Ergebnisse. TraderOS verspricht keinen Gewinn, verwahrt keine Kundengelder und stellt Prognosen nicht als Gewissheit dar; der Trader entscheidet selbst.",
  "Traders currently piece together charts, broker tools, indicator subscriptions, spreadsheets and social signal groups. Performance reporting is inconsistent and losing calls can disappear.":
    "Trader setzen heute Charts, Brokerwerkzeuge, Indikator-Abos, Tabellen und soziale Signalgruppen zusammen. Leistungsberichte sind uneinheitlich und Verlustsignale können verschwinden.",
  "UK self-directed traders across forex, indices, commodities and crypto, followed only by countries where product, promotion and data rules permit launch.":
    "Selbstentscheidende Trader im Vereinigten Königreich für Devisen, Indizes, Rohstoffe und Kryptowährungen; weitere Länder erst, wenn Produkt-, Werbe- und Datenregeln den Start erlauben.",
  "TraderOS earns only from trader subscriptions. Brokers, exchanges and data providers are integrations or suppliers, not a second paying customer side, and TraderOS does not take a share of trading gains or losses.":
    "TraderOS verdient ausschließlich an Trader-Abos. Broker, Börsen und Datenanbieter sind Integrationen oder Lieferanten und keine zweite zahlende Kundenseite; TraderOS erhält keinen Anteil an Handelsgewinnen oder -verlusten.",

  "Families, activities and community in one place":
    "Familien, Aktivitäten und Gemeinschaft an einem Ort",
  "BaytCircle is a Gulf family-and-community hub for local residents, expatriate families and home educators. Families use it free to find trusted groups, arrange meetups and events, discover classes and activities, and book spare capacity at swimming pools, soft-play centres, sports spaces, learning venues and other family-friendly places.":
    "BaytCircle ist ein Familien- und Gemeinschaftszentrum für Einheimische, zugezogene Familien und Homeschooling-Gruppen in der Golfregion. Familien nutzen es kostenlos, um vertrauenswürdige Gruppen zu finden, Treffen und Veranstaltungen zu organisieren, Kurse und Aktivitäten zu entdecken und freie Kapazitäten in Schwimmbädern, Indoor-Spielplätzen, Sportflächen, Lernorten und anderen familienfreundlichen Einrichtungen zu buchen.",
  "Family activities, home-education groups, community events and underused venue capacity across the UAE first, followed by selected Gulf cities.":
    "Zunächst Familienaktivitäten, Homeschooling-Gruppen, Gemeinschaftsveranstaltungen und ungenutzte Kapazitäten von Einrichtungen in den VAE, danach ausgewählte Städte der Golfregion.",
  "Free users are parents, guardians, children, home-educating families, expatriates and local residents. Paying customers are family venues, activity providers, tutors, clubs and community organisations that claim profiles and use booking, promotion and administration tools.":
    "Kostenlose Nutzer sind Eltern, Erziehungsberechtigte, Kinder, Homeschooling-Familien, Zugezogene und Einheimische. Zahlende Kunden sind Familienorte, Aktivitätsanbieter, Tutoren, Vereine und Gemeinschaftsorganisationen, die Profile übernehmen und Buchungs-, Werbe- und Verwaltungswerkzeuge nutzen.",
  "Gulf cities already have many families, activities and useful venues, but information is scattered across messaging groups, social pages and individual booking systems. Families struggle to find the right local option, while pools, soft-play centres, classrooms and clubs have unsold spaces and quiet times.":
    "In den Golfstädten gibt es bereits viele Familien, Aktivitäten und geeignete Orte, doch Informationen sind auf Nachrichtengruppen, soziale Seiten und einzelne Buchungssysteme verteilt. Familien finden nur schwer das passende Angebot in ihrer Nähe, während Schwimmbäder, Indoor-Spielplätze, Kursräume und Vereine freie Plätze und ruhige Zeiten haben.",
  "Build a trusted local directory area by area, add factual venue and activity profiles, clearly label unclaimed entries and invite each provider to claim and verify its page. Families use BaytCircle free to discover groups, organise events and book suitable activities. Providers pay for profile control, live availability, bookings, customer communication and promotion of spare or off-peak capacity, while keeping the full price of their service apart from normal payment-processing charges.":
    "Gebiet für Gebiet entsteht ein vertrauenswürdiges lokales Verzeichnis mit sachlichen Profilen von Orten und Aktivitäten. Nicht übernommene Einträge werden klar gekennzeichnet und Anbieter zur Prüfung und Übernahme eingeladen. Familien nutzen BaytCircle kostenlos, um Gruppen zu finden, Veranstaltungen zu organisieren und passende Aktivitäten zu buchen. Anbieter zahlen für Profilkontrolle, Live-Verfügbarkeit, Buchungen, Kundenkommunikation und die Bewerbung freier oder schwacher Zeiten und behalten den vollen Preis ihrer Leistung abzüglich normaler Zahlungsabwicklungskosten.",
  "Families currently search social media, messaging groups, school chats and separate venue websites. Organisers use spreadsheets and payment links, while many venues cannot easily publish quiet-time capacity to suitable nearby families.":
    "Familien suchen heute in sozialen Medien, Nachrichtengruppen, Schulchats und auf einzelnen Websites. Organisatoren nutzen Tabellen und Zahlungslinks, während viele Einrichtungen freie Kapazitäten in ruhigen Zeiten nicht gezielt nahe gelegenen Familien anbieten können.",
  "Parents, guardians, children, home educators, expatriates and local residents in Gulf cities, together with family venues, tutors, clubs and community organisations.":
    "Eltern, Erziehungsberechtigte, Kinder, Homeschooling-Familien, Zugezogene und Einheimische in Golfstädten sowie Familienorte, Tutoren, Vereine und Gemeinschaftsorganisationen.",
  "BaytCircle earns only from provider and organisation subscriptions for claimed profiles, booking tools and promotion. Families use the platform free, and providers retain their activity or venue income apart from normal payment-processing charges.":
    "BaytCircle verdient ausschließlich an Anbieter- und Organisationsabos für übernommene Profile, Buchungswerkzeuge und Werbung. Familien nutzen die Plattform kostenlos; Anbieter behalten ihre Aktivitäts- oder Ortseinnahmen abzüglich normaler Zahlungsabwicklungskosten.",

  "U.S. tax returns, prepared wherever you live":
    "US-Steuererklärungen, unabhängig von Ihrem Wohnort",
  "TaxCenda prepares and files U.S. federal and applicable state tax returns for taxpayer clients living in the United States or abroad. Each case is reviewed by an IRS Enrolled Agent or another appropriately authorised U.S. tax professional, with secure document collection, clear fixed pricing, electronic signature and filing through an authorised IRS e-file provider where the return is eligible for e-file.":
    "TaxCenda erstellt und übermittelt US-Bundessteuererklärungen und gegebenenfalls Erklärungen einzelner Bundesstaaten für Steuerpflichtige in den USA oder im Ausland. Jeder Fall wird von einem IRS Enrolled Agent oder einer anderen entsprechend autorisierten US-Steuerfachkraft geprüft. Dazu gehören sichere Dokumentenerfassung, klare Festpreise, elektronische Unterschrift und die Übermittlung über einen autorisierten IRS-E-File-Anbieter, sofern die Erklärung elektronisch eingereicht werden kann.",
  "U.S. citizens, residents, expatriates, non-residents and eligible small businesses with U.S. federal or state filing obligations, including clients who live outside the United States.":
    "US-Staatsbürger, Ansässige, im Ausland lebende Personen, Nichtansässige und geeignete Kleinunternehmen mit US-Bundes- oder Bundesstaaten-Erklärungspflichten, einschließlich Kunden außerhalb der USA.",
  "The single paying side is the taxpayer client: individuals, families, expatriates, non-residents and eligible small businesses purchasing U.S. return preparation and filing. The IRS, tax authorities and professional partners are not charged by TaxCenda.":
    "Die einzige zahlende Seite ist der steuerpflichtige Kunde: Privatpersonen, Familien, im Ausland lebende Personen, Nichtansässige und geeignete Kleinunternehmen, die Erstellung und Einreichung einer US-Steuererklärung kaufen. IRS, Steuerbehörden und Fachpartner zahlen nicht an TaxCenda.",
  "U.S. tax filing can remain compulsory even when a person lives abroad, while non-residents and internationally connected businesses face unfamiliar forms, deadlines, income classifications and identity requirements. Generic do-it-yourself software does not always explain cross-border facts clearly, and local accountants outside the U.S. may not prepare or e-file U.S. returns.":
    "Eine US-Steuererklärung kann auch bei Wohnsitz im Ausland erforderlich bleiben. Nichtansässige und international verbundene Unternehmen treffen auf ungewohnte Formulare, Fristen, Einkommensarten und Identitätsanforderungen. Allgemeine Selbsthilfe-Software erklärt grenzüberschreitende Sachverhalte nicht immer verständlich, und lokale Buchhalter außerhalb der USA erstellen oder übermitteln häufig keine US-Erklärungen.",
  "One secure case from eligibility check to filed return. The client answers a plain-language questionnaire, uploads evidence and receives a fixed scope and price. A suitably credentialed U.S. tax professional prepares and reviews the return, explains important positions, obtains the required authorisation and files through the appropriate authorised channel. TaxCenda does not promise a refund or invent deductions, and the client approves the completed return before filing.":
    "Ein sicherer Fall von der Pflichtprüfung bis zur eingereichten Erklärung. Der Kunde beantwortet verständliche Fragen, lädt Nachweise hoch und erhält einen festen Leistungsumfang und Preis. Eine entsprechend qualifizierte US-Steuerfachkraft erstellt und prüft die Erklärung, erläutert wichtige Positionen, holt die erforderliche Zustimmung ein und reicht über den passenden autorisierten Weg ein. TaxCenda verspricht keine Erstattung, erfindet keine Abzüge und reicht erst nach Freigabe durch den Kunden ein.",
  "Clients use do-it-yourself software, a U.S. tax firm, an expatriate-tax specialist or a local accountant who may then need a separate U.S. preparer. Documents, questions, signatures and filing status are often spread across email and several portals.":
    "Kunden nutzen Selbsthilfe-Software, eine US-Steuerkanzlei, einen Spezialisten für Auslandsfälle oder einen lokalen Buchhalter, der möglicherweise zusätzlich einen US-Ersteller benötigt. Unterlagen, Fragen, Unterschriften und Einreichungsstatus verteilen sich häufig auf E-Mails und mehrere Portale.",
  "Taxpayer clients in the United States and abroad who have supported U.S. federal or state filing needs, including individuals, expatriates, non-residents and eligible small businesses.":
    "Steuerpflichtige Kunden in den USA und im Ausland mit unterstützten US-Bundes- oder Bundesstaaten-Erklärungspflichten, darunter Privatpersonen, im Ausland lebende Personen, Nichtansässige und geeignete Kleinunternehmen.",
  "TaxCenda earns fixed preparation and filing fees or an annual taxpayer support plan from the taxpayer client only. It does not charge the IRS, tax authorities or professional partners and does not earn a percentage of a refund or tax saving.":
    "TaxCenda erhält ausschließlich vom steuerpflichtigen Kunden feste Erstellungs- und Einreichungsgebühren oder eine jährliche Betreuungspauschale. IRS, Steuerbehörden und Fachpartner werden nicht belastet; TaxCenda erhält keinen prozentualen Anteil an Erstattungen oder Steuerersparnissen.",

  "Manage and grow marketplace sales":
    "Marktplatzverkäufe verwalten und ausbauen",
  "Merqora is a sales-management and growth SaaS/app for sellers and agencies operating on Amazon and other online marketplaces. It brings product listings, stock, pricing, advertising, orders, account health, customer-service tasks and sales reporting into one workspace so teams can manage daily work and identify practical ways to grow.":
    "Merqora ist eine Software zur Verwaltung und zum Ausbau von Verkäufen für Verkäufer und Agenturen auf Amazon und anderen Online-Marktplätzen. Produktangebote, Bestand, Preise, Werbung, Bestellungen, Kontozustand, Kundenservice-Aufgaben und Verkaufsberichte kommen in einem Arbeitsbereich zusammen, damit Teams das Tagesgeschäft steuern und praktische Wachstumsmaßnahmen erkennen können.",
  "Amazon sellers, marketplace agencies and multichannel ecommerce businesses that need to manage and grow sales across several marketplace accounts, countries and product catalogues.":
    "Amazon-Verkäufer, Marktplatzagenturen und Multichannel-E-Commerce-Unternehmen, die Verkäufe über mehrere Marktplatzkonten, Länder und Produktkataloge verwalten und ausbauen müssen.",
  "The paying customers are Amazon and other online-marketplace sellers, seller agencies and ecommerce teams. Shoppers and marketplace customers are not charged by Merqora.":
    "Zahlende Kunden sind Verkäufer auf Amazon und anderen Online-Marktplätzen, Verkäuferagenturen und E-Commerce-Teams. Käufer und Marktplatzkunden zahlen keine Merqora-Gebühr.",
  "Marketplace sellers often switch between separate seller portals, advertising screens, spreadsheets, stock systems and reporting tools. Agencies repeat the same work across client accounts, while important listing, inventory, advertising and account-health problems can be missed until sales fall.":
    "Marktplatzverkäufer wechseln häufig zwischen getrennten Verkäuferportalen, Werbeansichten, Tabellen, Bestandssystemen und Berichtswerkzeugen. Agenturen wiederholen dieselbe Arbeit für mehrere Kundenkonten, während wichtige Probleme bei Angeboten, Bestand, Werbung oder Kontozustand bis zu einem Umsatzrückgang unbemerkt bleiben können.",
  "One clear workspace for running and improving marketplace sales. Merqora gathers authorised account data, shows the actions that need attention, helps teams improve listings and advertising, tracks stock and margins, and reports which products, marketplaces and campaigns are producing sustainable sales. The seller remains in control of every marketplace change and budget.":
    "Ein übersichtlicher Arbeitsbereich zur Steuerung und Verbesserung von Marktplatzverkäufen. Merqora sammelt autorisierte Kontodaten, zeigt erforderliche Maßnahmen, hilft Teams bei der Verbesserung von Angeboten und Werbung, verfolgt Bestand und Marge und zeigt, welche Produkte, Marktplätze und Kampagnen nachhaltige Verkäufe erzielen. Der Verkäufer behält die Kontrolle über jede Änderung und jedes Budget.",
  "Sellers currently work inside each marketplace portal and add separate research, advertising, inventory and reporting tools. Agencies then combine client information in spreadsheets and presentations, creating repeated work and delayed decisions.":
    "Verkäufer arbeiten heute in jedem Marktplatzportal und ergänzen getrennte Werkzeuge für Recherche, Werbung, Bestand und Berichte. Agenturen führen Kundendaten anschließend in Tabellen und Präsentationen zusammen, was Arbeit wiederholt und Entscheidungen verzögert.",
  "Amazon and other supported marketplace sellers, marketplace agencies and multichannel ecommerce teams managing products in one or more countries.":
    "Verkäufer auf Amazon und anderen unterstützten Marktplätzen, Marktplatzagenturen und Multichannel-E-Commerce-Teams, die Produkte in einem oder mehreren Ländern verwalten.",
  "Merqora earns business subscriptions from sellers and agencies, plus optional onboarding and approved integration fees. Shoppers are not charged, and Merqora does not take a percentage of marketplace sales.":
    "Merqora verdient an Geschäftsabos von Verkäufern und Agenturen sowie optionalen Einrichtungs- und freigegebenen Integrationsgebühren. Käufer zahlen nichts, und Merqora erhält keinen prozentualen Anteil an Marktplatzverkäufen.",

  "Merqano creates and runs separate ecommerce websites for customer businesses from one shared system. Each customer gets its own branded online shop, products, orders, payments, delivery rules, staff access and reports, while Merqano maintains the underlying technology centrally.":
    "Merqano erstellt und betreibt getrennte E-Commerce-Websites für Geschäftskunden mit einem gemeinsamen System. Jeder Kunde erhält einen eigenen Markenshop mit Produkten, Bestellungen, Zahlungen, Lieferregeln, Mitarbeitendenzugängen und Berichten, während Merqano die zugrunde liegende Technik zentral pflegt.",
  "Global spending on ecommerce website platforms, online-shop software and business website services.":
    "Weltweite Ausgaben für E-Commerce-Website-Plattformen, Onlineshop-Software und Website-Dienstleistungen für Unternehmen.",
  "Independent retailers, growing brands, franchise businesses and agencies that need a professional branded ecommerce website.":
    "Unabhängige Händler, wachsende Marken, Franchiseunternehmen und Agenturen, die eine professionelle E-Commerce-Website mit eigener Marke benötigen.",
  "Many businesses need their own professional ecommerce website but custom development is expensive and slow, while maintaining separate systems for every customer repeats the same technical work. Merqano provides products, checkout, payments, orders, delivery, staff roles and reporting through one maintained platform, while every customer receives a separate branded website.":
    "Viele Unternehmen benötigen eine eigene professionelle E-Commerce-Website, doch eine individuelle Entwicklung ist teuer und langsam. Getrennte Systeme für jeden Kunden wiederholen dieselbe technische Arbeit. Merqano stellt Produkte, Kasse, Zahlungen, Bestellungen, Lieferung, Mitarbeitendenrechte und Berichte über eine gepflegte Plattform bereit, während jeder Kunde eine getrennte Website mit eigener Marke erhält.",
  "Give each customer business its own professional ecommerce website without rebuilding the technology each time. The customer controls its branding, products, prices, orders, staff and customer relationships, while Merqano provides the secure shared commerce system, updates and support behind it.":
    "Jedem Geschäftskunden eine eigene professionelle E-Commerce-Website geben, ohne die Technik jedes Mal neu zu bauen. Der Kunde kontrolliert Marke, Produkte, Preise, Bestellungen, Mitarbeitende und Kundenbeziehungen; Merqano stellt das sichere gemeinsame Handelssystem, Aktualisierungen und Support im Hintergrund bereit.",
  "Businesses currently commission a custom ecommerce build or assemble a shop from a platform, themes, extensions and agency support. Merqano provides each customer with a separate branded website while maintaining the repeated technology and updates through one shared system.":
    "Unternehmen beauftragen heute eine individuelle E-Commerce-Entwicklung oder setzen einen Shop aus Plattform, Designvorlagen, Erweiterungen und Agenturhilfe zusammen. Merqano gibt jedem Kunden eine getrennte Website mit eigener Marke und pflegt die wiederkehrende Technik und Aktualisierungen in einem gemeinsamen System.",

  "Every meal is a blessing":
    "Jede Mahlzeit ist ein Segen",
  "Ni'mah is a complete surplus-food marketplace for Saudi Arabia and Pakistan. Restaurants, cafés, bakeries, hotels, supermarkets, caterers and other food businesses list good unsold food at a reduced price before it is wasted, and nearby customers discover, reserve, pay for and collect it during a stated collection window.":
    "Ni'mah ist ein vollständiger Marktplatz für überschüssige Lebensmittel in Saudi-Arabien und Pakistan. Restaurants, Cafés, Bäckereien, Hotels, Supermärkte, Caterer und andere Lebensmittelbetriebe bieten gute unverkaufte Lebensmittel günstiger an, bevor sie verschwendet werden. Kunden in der Nähe finden, reservieren, bezahlen und holen sie innerhalb eines angegebenen Zeitfensters ab.",
  "Surplus-food rescue and discounted local food across Saudi Arabia and Pakistan, beginning with dense city areas where many food outlets and customers are close together.":
    "Rettung überschüssiger Lebensmittel und günstige lokale Lebensmittel in Saudi-Arabien und Pakistan, zunächst in dichten Stadtgebieten mit vielen nahe beieinanderliegenden Betrieben und Kunden.",
  "Paying customers are food businesses with safe unsold food. Consumers use Ni'mah free to find and buy discounted food directly from participating outlets.":
    "Zahlende Kunden sind Lebensmittelbetriebe mit sicheren unverkauften Lebensmitteln. Verbraucher nutzen Ni'mah kostenlos, um günstige Lebensmittel teilnehmender Betriebe zu finden und direkt zu kaufen.",
  "Food businesses regularly finish the day with safe food that may no longer sell at full price. Throwing it away loses the ingredient cost, staff effort and possible income, while nearby families and workers are looking for affordable meals. Ni'mah connects that surplus with local demand before the safe collection deadline.":
    "Lebensmittelbetriebe beenden den Tag regelmäßig mit sicheren Lebensmitteln, die sich nicht mehr zum vollen Preis verkaufen lassen. Die Entsorgung verliert Warenwert, Arbeitszeit und mögliche Einnahmen, während Familien und Beschäftigte in der Nähe bezahlbare Mahlzeiten suchen. Ni'mah verbindet diese Überschüsse vor dem sicheren Abholende mit lokaler Nachfrage.",
  "Food outlets publish a limited surplus offer with contents or category, quantity, reduced price, allergens and collection time. Nearby customers reserve and pay, receive a collection code and collect directly from the outlet. Businesses recover value and reduce waste; customers get affordable food; Ni'mah organises the marketplace, payment record, availability and collection journey.":
    "Lebensmittelbetriebe veröffentlichen ein begrenztes Überschussangebot mit Inhalt oder Kategorie, Menge, reduziertem Preis, Allergenen und Abholzeit. Kunden in der Nähe reservieren und bezahlen, erhalten einen Abholcode und holen direkt beim Betrieb ab. Betriebe gewinnen Wert zurück und reduzieren Abfall, Kunden erhalten bezahlbare Lebensmittel und Ni'mah organisiert Marktplatz, Zahlungsnachweis, Verfügbarkeit und Abholung.",
  "Food outlets currently discount items informally near closing, post offers on social media, give food away or dispose of it. Customers cannot see all nearby surplus in one live search, and businesses cannot reliably reserve quantities or measure recovered value.":
    "Lebensmittelbetriebe reduzieren heute kurz vor Ladenschluss informell Preise, veröffentlichen Angebote in sozialen Medien, geben Lebensmittel ab oder entsorgen sie. Kunden sehen nicht alle Überschüsse in der Nähe in einer Live-Suche, und Betriebe können Mengen nicht zuverlässig reservieren oder den zurückgewonnenen Wert messen.",
  "Restaurants, cafés, bakeries, hotels, supermarkets, caterers and other food outlets in Saudi and Pakistani cities, together with nearby value-conscious customers.":
    "Restaurants, Cafés, Bäckereien, Hotels, Supermärkte, Caterer und andere Lebensmittelbetriebe in saudischen und pakistanischen Städten sowie preisbewusste Kunden in der Nähe.",
  "Ni'mah earns subscriptions and optional business tools from participating food outlets only. Customers pay the outlet's displayed discounted food price but no separate Ni'mah platform fee, and Ni'mah does not take a percentage of each food sale.":
    "Ni'mah verdient ausschließlich an Abos und optionalen Geschäftswerkzeugen teilnehmender Lebensmittelbetriebe. Kunden zahlen den angezeigten reduzierten Lebensmittelpreis an den Betrieb, aber keine separate Ni'mah-Plattformgebühr; Ni'mah erhält keinen prozentualen Anteil an Lebensmittelverkäufen.",
};
