import json

translations = {
    "Team availability, attendance confirmation and standby substitutes": "Team-Verfügbarkeit, Anwesenheitsbestätigung und Ersatzspieler auf Abruf",
    "Share the venue cost, collect deposits and match fees without an Athlyvo player service charge": "Teilen Sie die Kosten für den Austragungsort, ziehen Sie Kautionen und Spielgebühren ein – ohne Athlyvo-Servicegebühr für Spieler",
    "Free profiles and discovery for coaches, trainers, referees, umpires, scorers and analysts": "Kostenlose Profile und Suche für Coaches, Trainer, Schiedsrichter, Wertungsrichter und Analysten",
    "Off-peak pricing and promoted empty slots for venues": "Nebentarife und beworbene Leerzeiten für Austragungsorte",
    "Waitlists, reminders, cancellation rules and replacement players to improve booking certainty": "Wartelisten, Erinnerungen, Stornierungsregeln und Ersatzspieler zur Erhöhung der Buchungssicherheit",
    "Car-share coordination without operating as a transport provider": "Fahrgemeinschafts-Koordination, ohne als Transportunternehmen aufzutreten",
    "Scores, tables, player records and optional performance analysis": "Spielstände, Tabellen, Spielerstatistiken und optionale Leistungsanalyse",
    "Privacy controls and optional face or body blurring for permitted video": "Datenschutzeinstellungen und optionale Gesichts- oder Körperverpixelung für freigegebene Videos",
    "Venue operating system: calendar, pricing, access, staff, maintenance and reporting": "Betriebssystem für Austragungsorte: Kalender, Preisgestaltung, Zugang, Personal, Wartung und Reporting",
    "Council, school and community programme reporting": "Reporting für Kommunen, Schulen und Gemeinschaftsprogramme",
    "Players, organisers, teams, clubs, coaches and officials: free": "Spieler, Organisatoren, Teams, Vereine, Coaches und Offizielle: kostenlos",
    "Venue claim and verification: free, followed by a 60-day full trial": "Anspruchsübernahme und Verifizierung von Austragungsorten: kostenlos, gefolgt von einer 60-tägigen Testphase mit vollem Funktionsumfang",
    "Venue Starter £39/month for one bookable venue": "Venue Starter £39/Monat für einen buchbaren Austragungsort",
    "Venue Growth £79/month for more spaces, promotions and reporting": "Venue Growth £79/Monat für mehr Flächen, Werbeaktionen und Reporting",
    "Venue Pro £149/month for advanced operations, staff and integrations": "Venue Pro £149/Monat für fortgeschrittene Betriebsabläufe, Personal und Integrationen",
    "Multi-site, council and leisure groups from £299/month": "Standortübergreifende Lösungen, Kommunen und Freizeitgruppen ab £299/Monat",
    "No Athlyvo service fee for players and no commission on the venue's booking value; card-processing costs are shown separately to the venue": "Keine Athlyvo-Servicegebühr für Spieler und keine Provision auf den Buchungswert des Austragungsorts; Kartenzahlungsgebühren werden dem Betreiber separat ausgewiesen",
    "Discover, join, book, pay, confirm and track sport.": "Sport entdecken, beitreten, buchen, bezahlen, bestätigen und verfolgen.",
    "The same player and organiser journey on Android.": "Das gleiche Erlebnis für Spieler und Organisatoren auf Android.",
    "Free tools for teams, availability, fixtures, results and communication.": "Kostenlose Tools für Teams, Verfügbarkeit, Spielpläne, Ergebnisse und Kommunikation.",
    "Free discovery profiles for coaches, trainers and officials.": "Kostenlose Suchprofile für Coaches, Trainer und Offizielle.",
    "The paid product: claims, calendars, slots, pricing, bookings, access, customers and reporting.": "Das kostenpflichtige Produkt: Ansprüche, Kalender, Zeitfenster, Preise, Buchungen, Zugang, Kunden und Reporting.",
    "Verification, safeguarding, disputes, payments, content and partner controls.": "Verifizierung, Kinderschutz/Sicherheit, Streitbeilegung, Zahlungen, Inhalte und Partnerkontrolle.",
    "Player (free)": "Spieler (kostenlos)",
    "Finds a nearby activity, joins, pays only the agreed share of the venue price and receives confirmed updates.": "Findet Aktivitäten in der Nähe, tritt bei, zahlt nur den vereinbarten Anteil des Preises für den Austragungsort und erhält Bestätigungs-Updates.",
    "Organiser or captain (free)": "Organisator oder Kapitän (kostenlos)",
    "Books the venue, confirms the team, fills gaps and collects each person's share.": "Bucht den Austragungsort, bestätigt das Team, füllt Lücken und sammelt den Kostenanteil jeder Person ein.",
    "Club administrator (free)": "Vereinsadministrator (kostenlos)",
    "Runs teams, members, fixtures, officials and results without an Athlyvo subscription.": "Verwaltet Teams, Mitglieder, Spielpläne, Offizielle und Ergebnisse ohne Athlyvo-Abonnement.",
    "Coach or official (free)": "Coach oder Offizieller (kostenlos)",
    "Creates a profile, shows availability and can be found by local organisers and venues.": "Erstellt ein Profil, zeigt Verfügbarkeiten an und kann von lokalen Organisatoren und Austragungsorten gefunden werden.",
    "Venue operator (paying customer)": "Betreiber des Austragungsorts (zahlender Kunde)",
    "Claims and verifies its profile, publishes live slots, promotes quiet periods and runs bookings from one calendar.": "Übernimmt und verifiziert sein Profil, veröffentlicht Live-Slots, bewirbt ruhigere Zeiten und verwaltet Buchungen über einen zentralen Kalender.",
    "Council or leisure group (paying customer)": "Kommune oder Freizeitgruppe (zahlender Kunde)",
    "Manages several facilities, promotes participation and sees programme and usage reporting.": "Verwaltet mehrere Einrichtungen, fördert die Teilnahme und erhält Reportings zu Programmen und Auslastung.",
    "Venues and players already exist in large numbers, but discovery, availability, team organisation, payments and confirmations are split across search engines, separate venue sites, phone calls, spreadsheets and message groups.": "Austragungsorte und Spieler sind bereits in großer Zahl vorhanden, aber Suche, Verfügbarkeit, Teamorganisation, Zahlungen und Bestätigungen verteilen sich auf Suchmaschinen, separate Websites der Betreiber, Telefonanrufe, Tabellenkalkulationen und Messenger-Gruppen.",
    "Millions of UK adults and children participate in grassroots, recreational and fitness activity, supported by thousands of public, private, school, club and community venues.": "Millionen von Erwachsenen und Kindern in Großbritannien nehmen an Breitensport-, Freizeit- und Fitnessaktivitäten teil, unterstützt von Tausenden öffentlicher, privater, schulischer, vereinsbasierter und kommunaler Austragungsorte.",
    "Free access removes the main barrier to bringing large numbers of players, teams and organisers into one network": "Der kostenlose Zugang beseitigt die größte Hürde, um eine große Anzahl von Spielern, Teams und Organisatoren in einem Netzwerk zu vereinen",
    "Pre-listing lawful public venue information creates useful postcode coverage before every operator has joined": "Die Vorab-Listung rechtmäßiger öffentlicher Informationen zu Austragungsorten schafft eine nützliche Postleitzahlenabdeckung, noch bevor jeder Betreiber beigetreten ist",
    "Claimed and verified profiles turn fragmented venue information into dependable live availability": "Übernommene und verifizierte Profile verwandeln fragmentierte Informationen über Austragungsorte in verlässliche Live-Verfügbarkeiten",
    "Empty-place filling, confirmations and off-peak offers increase use of facilities without building new ones": "Die Besetzung freier Plätze, Bestätigungen und Nebentarif-Angebote erhöhen die Auslastung von Einrichtungen, ohne neue bauen zu müssen",
    "Venue-only subscriptions make the payer and value exchange simple: venues pay because Athlyvo helps them fill and run capacity": "Abonnements nur für Betreiber machen den Zahlungs- und Mehrwertaustausch einfach: Betreiber zahlen, weil Athlyvo ihnen hilft, Kapazitäten auszulasten und zu verwalten",
    "The UK beachhead can be launched locally and expanded sport by sport and area by area": "Der Brückenkopf im UK kann lokal gestartet und Sportart für Sportart sowie Gebiet für Gebiet erweitert werden",
    "A marketplace needs both local players and local venue supply": "Ein Marktplatz benötigt sowohl lokale Spieler als auch ein lokales Angebot an Austragungsorten",
    "Pre-list venues from lawful public sources, label unclaimed records clearly, recruit players through clubs and community networks, and expand postcode by postcode and sport by sport.": "Austragungsorte aus rechtmäßigen öffentlichen Quellen vorab listen, nicht übernommene Datensätze klar kennzeichnen, Spieler über Vereine und Gemeinschaftsnetzwerke gewinnen und Postleitzahl für Postleitzahl sowie Sportart für Sportart expandieren.",
    "Unclaimed venue information may be incomplete or become outdated": "Nicht übernommene Informationen zu Austragungsorten können unvollständig sein oder veralten",
    "Show the source and last-checked date, provide correction and removal routes, suppress unverified availability and require ownership checks before a venue can manage bookings.": "Quelle und Datum der letzten Überprüfung anzeigen, Wege für Korrekturen und Löschungen bereitstellen, unverifizierte Verfügbarkeiten unterdrücken und Eigentumsprüfungen verlangen, bevor ein Betreiber Buchungen verwalten kann.",
    "Safeguarding, filming and personal data are sensitive": "Kinderschutz/Sicherheit, Filmen und personenbezogene Daten sind sensible Themen",
    "Age-aware permissions, guardian consent, private defaults, reporting, role controls and optional video blurring.": "Altersabhängige Berechtigungen, Zustimmung der Erziehungsberechtigten, datenschutzfreundliche Standardeinstellungen, Reporting, Rollenkontrollen und optionale Videoverpixelung.",
    "Cancellations and no-shows create disputes": "Stornierungen und Nichterscheinen führen zu Streitigkeiten",
    "Clear policies, attendance confirmation, standby replacements, deposits and evidence-based refund workflows.": "Klare Richtlinien, Anwesenheitsbestätigungen, Ersatzspieler auf Abruf, Kautionen und belegbasierte Erstattungsabläufe.",
    "Different sports and venues have different rules": "Verschiedene Sportarten und Austragungsorte haben unterschiedliche Regeln",
    "Use a common booking core with configurable sport, venue and governing-body templates.": "Nutzung eines gemeinsamen Buchungskerns mit konfigurierbaren Vorlagen für Sportarten, Austragungsorte und Verbände.",
    "Playfinder and venue-booking directories": "Playfinder und Verzeichnisse für Sportstättenbuchungen",
    "Existing venue supply and search traffic": "Bestehendes Angebot an Austragungsorten und Suchverkehr",
    "Athlyvo is free to players and continues after discovery with confirmations, shared venue costs, substitutes, results and repeat play, while venues get an operating system.": "Athlyvo ist für Spieler kostenlos und geht über die Suche hinaus mit Bestätigungen, geteilten Kosten für Austragungsorte, Ersatzspielern, Ergebnissen und wiederholtem Spielen, während Betreiber ein Betriebssystem erhalten.",
    "Spond, TeamApp and club tools": "Spond, TeamApp und Vereinstools",
    "Strong team communication and attendance": "Starke Teamkommunikation und Anwesenheit",
    "Athlyvo keeps team tools free and connects them to public venue discovery, live slots, officials, coaches and bookings.": "Athlyvo hält Team-Tools kostenlos und verbindet sie mit der öffentlichen Suche nach Austragungsorten, Live-Slots, Offiziellen, Coaches und Buchungen.",
    "WhatsApp, spreadsheets and separate payment links": "WhatsApp, Tabellenkalkulationen und separate Zahlungslinks",
    "Athlyvo remains free for participants but gives both sides one confirmed record of the slot, attendance, money and changes.": "Athlyvo bleibt für Teilnehmer kostenlos, bietet aber beiden Seiten einen bestätigten Datensatz über das Zeitfenster, die Anwesenheit, Zahlungen und Änderungen.",
    "Only venues pay: monthly subscriptions for claimed venue profiles, booking tools and operating features": "Nur Betreiber zahlen: monatliche Abonnements für übernommene Profile, Buchungstools und Betriebsfunktionen",
    "Venues can buy promoted placement and off-peak campaigns; these are clearly labelled": "Betreiber können hervorgehobene Platzierungen und Nebentarif-Kampagnen erwerben; diese sind klar gekennzeichnet",
    "Venue groups, councils and leisure trusts pay for multi-site onboarding, integrations and reporting": "Betreibergruppen, Kommunen und Freizeit-Trusts zahlen für standortübergreifendes Onboarding, Integrationen und Reporting",
    "Players, organisers, teams, clubs, coaches and officials are not charged by Athlyvo": "Spieler, Organisatoren, Teams, Vereine, Coaches und Offizielle werden von Athlyvo nicht zur Kasse gebeten",
    "sports venues, leisure trusts, schools with bookable facilities and multi-site operators": "Sportstätten, Freizeit-Trusts, Schulen mit buchbaren Einrichtungen und standortübergreifende Betreiber",
    "Players, organisers, teams, clubs, coaches and officials use Athlyvo free": "Spieler, Organisatoren, Teams, Vereine, Coaches und Offizielle nutzen Athlyvo kostenlos",
    "venue subscription by locations, spaces and operating features": "Abonnement für Austragungsorte nach Standorten, Flächen und Betriebsfunktionen",
    "Vetted carer and provider network: DBS, references, right-to-work, training and insurance checks": "Überprüftes Netzwerk von Pflegekräften und Anbietern: Prüfung von DBS (polizeiliches Führungszeugnis), Referenzen, Arbeitsberechtigung, Ausbildung und Versicherung",
    "Postcode-based care matching by availability, skills, language and specialism": "Postleitzahlenbasierte Pflegevermittlung nach Verfügbarkeit, Fähigkeiten, Sprache und Spezialisierung",
    "Recurring or ad-hoc visit booking with carer and family confirmation": "Buchung von regelmäßigen oder Ad-hoc-Besuchen mit Bestätigung durch Pflegekraft und Familie",
    "Digital care plans with tasks, medications, observations and alerts": "Digitale Pflegepläne mit Aufgaben, Medikamenten, Beobachtungen und Warnmeldungen",
    "Real-time carer check-in / check-out with GPS, photo and visit notes": "Echtzeit-Check-in / Check-out der Pflegekraft mit GPS, Foto und Besuchsnotizen",
    "Family visibility portal: live rota, visit reports, expenses and care diary": "Transparenzportal für Familien: Live-Dienstplan, Besuchsberichte, Ausgaben und Pflegetagebuch",
    "Secure SEPA / Direct Debit / card payments and carer instant payouts": "Sichere SEPA- / Lastschrift- / Kartenzahlungen und Sofortauszahlungen an Pflegekräfte",
    "Agency and local-authority dashboard: scheduling, compliance, invoices, payroll exports": "Dashboard für Agenturen und Kommunen: Einsatzplanung, Compliance, Rechnungen, Lohnabrechnungsexporte",
    "CQC evidence pack: training records, incidents, audits and visit logs": "CQC-Nachweispaket: Schulungsunterlagen, Vorfälle, Audits und Besuchsprotokolle",
    "Two-way reviews and trust scoring for carers and families": "Gegenseitige Bewertungen und Trust-Scoring für Pflegekräfte und Familien",
    "Emergency cover pool with 24h availability": "Notfall-Pool mit 24-Stunden-Verfügbarkeit",
    "AI care-coordinator: suggests optimal rota, flags gaps and prepares visit summaries": "KI-Pflegekoordinator: schlägt optimale Dienstpläne vor, markiert Lücken und erstellt Besuchszusammenfassungen",
    "UK GDPR-compliant, CQC-aligned, hosted in the UK": "UK GDPR-konform, CQC-konform, gehostet im Vereinigten Königreich",
    "Families, care recipients and individual carers use the network free": "Familien, Pflegeempfänger und einzelne Pflegekräfte nutzen das Netzwerk kostenlos",
    "Families find, book and monitor care for their loved ones.": "Familien finden, buchen und überwachen die Pflege für ihre Angehörigen.",
    "On-the-go booking, notifications and visit updates for families.": "Buchung von unterwegs, Benachrichtigungen und Besuchsaktualisierungen für Familien.",
    "Same family experience on Android.": "Dasselbe Erlebnis für Familien auf Android.",
    "Carers view rota, check in/out, record notes and track earnings.": "Pflegekräfte sehen Dienstpläne ein, checken ein/aus, protokollieren Notizen und verfolgen ihre Einnahmen.",
    "Same carer experience on Android.": "Dasselbe Erlebnis für Pflegekräfte auf Android.",
    "Care agencies schedule staff, manage compliance, invoice and run payroll.": "Pflegeagenturen planen Personal, verwalten Compliance, stellen Rechnungen und führen die Lohnabrechnung durch.",
    "Local authority commissioners track placements, spend and outcomes.": "Beauftragte der Kommunalverwaltung verfolgen Platzierungen, Ausgaben und Ergebnisse.",
    "iTechLounge operations, vetting, trust & safety and reporting.": "iTechLounge-Betrieb, Überprüfung, Vertrauen & Sicherheit und Reporting.",
    "Integrations with local authority systems, payroll and CQC platforms.": "Integrationen mit Systemen der Kommunalverwaltung, Lohnabrechnungs- und CQC-Plattformen.",
    "Family care seeker": "Pflegesuchende Familie",
    "Finds a vetted local carer, books visits and sees live updates from every appointment.": "Findet eine geprüfte lokale Pflegekraft, bucht Besuche und sieht Live-Updates von jedem Termin.",
    "Self-funder": "Selbstzahler",
    "Manages private care budget, invoices and tax-deductible receipts in one place.": "Verwaltet das private Pflegebudget, Rechnungen und steuerlich absetzbare Belege an einem zentralen Ort.",
    "Domiciliary carer": "Häusliche Pflegekraft",
    "Accepts shifts, checks in/out, records care notes and gets paid quickly.": "Nimmt Schichten an, checkt ein/aus, protokolliert Pflegenotizen und wird schnell bezahlt.",
    "Care agency owner": "Inhaber einer Pflegeagentur",
    "Runs scheduling, compliance, billing and staff verification from one dashboard.": "Verwaltet Einsatzplanung, Compliance, Abrechnung und Personalüberprüfung über ein Dashboard.",
    "Local authority commissioner": "Beauftragter der Kommunalverwaltung",
    "Tracks spend, outcomes and provider quality across a patch.": "Verfolgt Ausgaben, Ergebnisse und Anbieterqualität in einem Bezirk.",
    "Support provider": "Unterstützungsanbieter",
    "Publishes specialist learning-disability, dementia or respite services.": "Veröffentlicht spezialisierte Dienste für Lernbehinderungen, Demenz oder Kurzzeitpflege (Respite).",
    "Home care in the UK is largely arranged through local authority brokerage lists, high-street care agencies that charge 30-50% mark-ups, or informal word-of-mouth. Digital platforms exist but are fragmented, often commission-based and weak on compliance workflow. Carers are frequently paid late through opaque systems and have no single app for rostering and notes.": "Die häusliche Pflege in Großbritannien wird größtenteils über Vermittlungslisten der Kommunen, herkömmliche Pflegeagenturen mit Aufschlägen von 30–50 % oder informelle Mundpropaganda organisiert. Digitale Plattformen existieren, sind jedoch fragmentiert, oft provisionsbasiert und weisen Schwächen bei Compliance-Workflows auf. Pflegekräfte werden häufig verspätet über undurchsichtige Systeme bezahlt und verfügen über keine einheitliche App für Dienstplanung und Notizen.",
    "≈1.6m people receive paid care at home; ≈450,000 paid carers; ≈2.5m unpaid carers.": "≈1,6 Mio. Menschen erhalten bezahlte häusliche Pflege; ≈450.000 bezahlte Pflegekräfte; ≈2,5 Mio. unbezahlte Pflegende.",
    "Carer supply density in rural areas": "Dichte des Pflegekräfteangebots in ländlichen Gebieten",
    "Launch in urban clusters with existing carer supply, partner with local colleges and training providers, offer referral bonuses.": "Start in städtischen Ballungsräumen mit bestehendem Pflegekräfteangebot, Partnerschaften mit lokalen Colleges und Ausbildungsanbietern, Angebot von Empfehlungsprämien.",
    "Safeguarding incident harms trust": "Sicherheitsvorfall schadet dem Vertrauen",
    "Mandatory DBS, insurance and reference checks, incident escalation, £10m liability cover, immediate suspension workflow and 24h trust-and-safety team.": "Verpflichtende DBS-, Versicherungs- und Referenzprüfungen, Eskalation von Vorfällen, Haftpflichtschutz in Höhe von £10 Mio., Workflow für sofortige Suspendierung und ein 24-Stunden-Vertrauens- und Sicherheitsteam.",
    "Local authority procurement cycles are slow": "Beschaffungszyklen der Kommunalverwaltung sind langsam",
    "Lead with self-funders and private agencies, then add authority modules once revenue is proven.": "Fokus zunächst auf Selbstzahler und private Agenturen, dann Hinzufügen von Kommunal-Modulen, sobald Umsätze belegt sind.",
    "Regulatory changes (CQC, minimum wage, travel time)": "Regulatorische Änderungen (CQC, Mindestlohn, Reisezeit)",
    "Shared compliance function monitors CQC and employment-law changes; rule updates are configuration, not code.": "Eine gemeinsame Compliance-Funktion überwacht Änderungen bei CQC und Arbeitsrecht; Regelaktualisierungen erfolgen über die Konfiguration, nicht über den Code.",
    "HomeTouch": "HomeTouch",
    "Established vetted carer platform with strong London/South East presence": "Etablierte Plattform für geprüfte Pflegekräfte mit starker Präsenz in London/Südostengland",
    "Flat subscription rather than 15-25% commission on every hour; full care-plan, agency and local-authority tools; UK-wide launch from day one": "Pauschales Abonnement statt 15–25 % Provision auf jede Stunde; vollständige Tools für Pflegepläne, Agenturen und Kommunalverwaltungen; UK-weiter Start ab dem ersten Tag",
    "Care.com": "Care.com",
    "Large directory of carers and household helpers": "Großes Verzeichnis von Pflegekräften und Haushaltshilfen",
    "DBS and insurance verification as standard, not optional; built-in care plans, check-ins and regulated-agency workflows rather than a simple directory": "DBS- und Versicherungsverifizierung als Standard, nicht optional; integrierte Pflegepläne, Check-ins und Workflows für regulierte Agenturen statt eines einfachen Verzeichnisses",
    "Traditional care agencies": "Traditionelle Pflegeagenturen",
    "Trusted local relationships and full regulatory responsibility": "Vertrauensvolle lokale Beziehungen und volle regulatorische Verantwortung",
    "Agencies use our SaaS for 30-50% less overhead, pass savings to families, and keep their own brand; families can still book agency-managed care": "Agenturen nutzen unser SaaS für 30–50 % weniger Verwaltungsaufwand, geben Ersparnisse an Familien weiter und behalten ihre eigene Marke; Familien können weiterhin agenturgeführte Pflege buchen",
    "Local authority brokerage": "Vermittlung durch Kommunalverwaltungen",
    "Funded placements and market reach": "Geförderte Platzierungen und Marktreichweite",
    "Digital commissioning, outcomes reporting and provider marketplace reduce admin cost and give families more choice": "Digitale Beauftragung, Ergebnis-Reporting und ein Marktplatz für Anbieter senken die Verwaltungskosten und bieten Familien mehr Auswahl",
    "Cera / Care UK": "Cera / Care UK",
    "National brand, trained workforce and NHS partnerships": "Nationale Marke, geschultes Personal und NHS-Partnerschaften",
    "Open network model lets families choose independent carers and local specialists; agencies keep their own identity and margin": "Ein offenes Netzwerkmodell ermöglicht es Familien, unabhängige Pflegekräfte und lokale Spezialisten zu wählen; Agenturen behalten ihre eigene Identität und Marge",
    "Landlord dashboard for every storefront, country and retailer programme": "Landlord-Dashboard für jeden Storefront, jedes Land und jedes Händlerprogramm",
    "Separate tenant domains, branding, roles, catalogues and analytics": "Separate Mandanten-Domains, Branding, Rollen, Kataloge und Analysen",
    "Approved retailer feed imports with normalisation and duplicate control": "Importe von freigegebenen Händler-Feeds mit Normalisierung und Dublettenkontrolle",
    "Affiliate-tag and deep-link management by tenant, country and campaign": "Management von Affiliate-Tags und Deep-Links nach Mandant, Land und Kampagne",
    "Country-aware routing to supported Amazon and regional marketplace programmes": "Länderabhängiges Routing zu unterstützten Amazon- und regionalen Marktplatzprogrammen",
    "Broken-link, unavailable-product and stale-price monitoring": "Überwachung von defekten Links, nicht verfügbaren Produkten und veralteten Preisen",
    "Buying-guide, comparison, review and collection content studio": "Content-Studio für Kaufberater, Vergleiche, Rezensionen und Kollektionen",
    "Human approval, source notes, affiliate disclosure and advertising controls": "Menschliche Freigabe, Quellenhinweise, Affiliate-Offenlegung und Werbekontrollen",
    "Search, email and social publishing workflows": "Publishing-Workflows für Suche, E-Mail und soziale Medien",
    "Traffic, click, order and confirmed-commission reporting": "Reporting für Traffic, Klicks, Bestellungen und bestätigte Provisionen",
    "Multi-language and multi-currency presentation": "Mehrsprachige und mehrwährungsfähige Darstellung",
    "White-label tenant onboarding for future external publishers": "White-Label-Mandanten-Onboarding für zukünftige externe Publisher",
    "Shoppers never pay Affivon": "Käufer zahlen niemals an Affivon",
    "Controls tenants, retailers, users, tracking, disclosures and portfolio reporting.": "Steuert Mandanten, Händler, Nutzer, Tracking, Offenlegungen und Portfolio-Reporting.",
    "Each storefront manages products, content, campaigns and its own results.": "Jeder Storefront verwaltet Produkte, Inhalte, Kampagnen und seine eigenen Ergebnisse.",
    "Creates, reviews and refreshes buying guides and comparisons.": "Erstellt, prüft und aktualisiert Kaufberater und Vergleiche.",
    "Imports approved retailer data and produces compliant tracked links.": "Importiert freigegebene Händlerdaten und erstellt konforme Tracking-Links.",
    "Portfolio owner": "Portfolio-Eigentümer",
    "Compares the performance and compliance of all storefronts from one dashboard.": "Vergleicht die Performance und Compliance aller Storefronts über ein zentrales Dashboard.",
    "Store manager": "Store-Manager",
    "Runs one niche brand without accessing another tenant's data.": "Verwaltet eine Nischenmarke, ohne auf die Daten anderer Mandanten zuzugreifen.",
    "Creates and refreshes useful commercial content with human approval.": "Erstellt und aktualisiert nützliche kommerzielle Inhalte mit menschlicher Freigabe.",
    "Affiliate operations manager": "Affiliate Operations Manager",
    "Maintains retailer programmes, tracking rules, disclosures and reconciliation.": "Pflegt Händlerprogramme, Tracking-Regeln, Offenlegungen und Abgleiche.",
    "Affiliate publishers commonly run separate WordPress sites, feeds, spreadsheets and retailer dashboards, making portfolio control and compliance difficult.": "Affiliate-Publisher betreiben üblicherweise separate WordPress-Seiten, Feeds, Tabellenkalkulationen und Händler-Dashboards, was die Portfoliokontrolle und Compliance erschwert.",
    "Millions of publishers and creators use affiliate programmes, while agencies and portfolio owners increasingly operate several niche sites.": "Millionen von Publishern und Creatorn nutzen Affiliate-Programme, während Agenturen und Portfolio-Eigentümer zunehmend mehrere Nischenseiten betreiben.",
    "One product and data engine supports ten revenue-producing storefronts": "Eine Produkt- und Daten-Engine unterstützt zehn umsatzgenerierende Storefronts",
    "No consumer stock, warehouse, checkout, delivery or returns operation": "Kein Lagerbestand für Verbraucher, kein Lager, kein Checkout, keine Lieferung oder Retourenabwicklung",
    "New countries, retailers and compliance changes are connected once for every tenant": "Neue Länder, Händler und Compliance-Änderungen werden einmalig für alle Mandanten angebunden",
    "Portfolio reporting shows which categories, content and markets deserve further investment": "Das Portfolio-Reporting zeigt, welche Kategorien, Inhalte und Märkte weitere Investitionen verdienen",
    "The landlord edition can later be licensed to other affiliate publishers and agencies": "Die Landlord-Edition kann später an andere Affiliate-Publisher und Agenturen lizenziert werden",
    "Dependence on third-party retailer programmes": "Abhängigkeit von Händlerprogrammen Dritter",
    "Support several approved retailers and countries, record terms per programme and never forecast unapproved partnerships.": "Unterstützung mehrerer freigegebener Händler und Länder, Erfassung der Bedingungen pro Programm und niemals Prognosen für nicht freigegebene Partnerschaften erstellen.",
    "Poor or duplicated content fails to win search traffic": "Minderwertiger oder duplizierter Content gewinnt keinen Suchverkehr",
    "Require useful original editorial content, human approval, source notes and quality thresholds before indexing.": "Verlangen von nützlichem, originärem redaktionellem Content, menschlicher Freigabe, Quellenhinweisen und Qualitätsschwellen vor der Indexierung.",
    "Ten stores spread editorial attention too thinly": "Zehn Stores verteilen die redaktionelle Aufmerksamkeit zu stark",
    "Launch categories in stages and use performance gates before expanding content or paid promotion.": "Einführung von Kategorien in Stufen und Nutzung von Performance-Gates vor der Erweiterung von Content oder bezahlter Werbung.",
    "FreshStore and affiliate-store builders": "FreshStore und Affiliate-Store-Builder",
    "Fast Amazon storefront setup": "Schnelle Einrichtung von Amazon-Storefronts",
    "Affivon is a true multi-tenant landlord with regional retailer routing, editorial workflow, link health and consolidated reporting across many owned brands.": "Affivon ist ein echter Multi-Tenant-Landlord mit regionalem Händler-Routing, redaktionellem Workflow, Link-Health-Check und konsolidiertem Reporting über viele eigene Marken hinweg.",
    "WordPress affiliate plugins": "WordPress-Affiliate-Plugins",
    "Large plugin ecosystem and low entry cost": "Großes Plugin-Ökosystem und geringe Einstiegskosten",
    "Affivon removes plugin maintenance and gives one controlled data, compliance and analytics layer across every tenant.": "Affivon macht die Plugin-Wartung überflüssig und bietet eine kontrollierte Daten-, Compliance- und Analyse-Ebene über alle Mandanten hinweg.",
    "Custom websites built separately": "Separat erstellte maßgeschneiderte Websites",
    "Complete design freedom": "Vollständige Designfreiheit",
    "A shared engine cuts repeated development and makes a successful content or integration improvement available to all stores.": "Eine gemeinsame Engine reduziert wiederholte Entwicklungsarbeit und macht erfolgreiche Inhalts- oder Integrationsverbesserungen für alle Stores verfügbar.",
    "external publishers, agencies and participating retail partners": "externe Publisher, Agenturen und teilnehmende Handelspartner",
    "publisher subscription plus business-paid affiliate income": "Publisher-Abonnement plus vom Unternehmen gezahltes Affiliate-Einkommen"
}

with open('/tmp/tr11.json', 'r') as f:
    original_keys = json.load(f)

result = {}
for key in original_keys:
    if key in translations:
        result[key] = translations[key]
    else:
        # Fallback to key if not found, but I should have all keys
        result[key] = key

with open('/tmp/de11.json', 'w', encoding='utf-8') as f:
    json.dump(result, f, ensure_ascii=False, indent=2)

print(f"Processed {len(result)} strings.")
