import json

translations = {
    "Rewards and cashback issuing": "Ausgabe von Belohnungen und Cashback",
    "Subscription billing and dunning": "Abonnement-Abrechnung und Mahnwesen",
    "Chargeback and dispute handling": "Abwicklung von Rückbuchungen und Streitfällen",
    "Unified reconciliation and ledger": "Einheitlicher Abgleich und Hauptbuch",
    "Reporting and revenue-share automation": "Automatisierung von Reporting und Umsatzbeteiligung",
    "Consumers are not charged by Zoryn Pay": "Endkunden werden von Zoryn Pay nicht belastet",
    "Payments, payouts, wallets": "Zahlungen, Auszahlungen, Wallets",
    "Merchant onboarding and reporting": "Händler-Onboarding und Reporting",
    "Reconciliation and settlement": "Abgleich und Abrechnung",
    "Hosted checkout and wallet": "Hosted Checkout und Wallet",
    "Group brand": "Konzernmarke",
    "Plugs in payments and payouts in days, not months.": "Integriert Zahlungen und Auszahlungen in Tagen, nicht Monaten.",
    "External marketplace": "Externer Marktplatz",
    "Gets escrow and split payouts without building them.": "Erhält Treuhand- und Split-Auszahlungen, ohne diese selbst entwickeln zu müssen.",
    "Onboards, sells and gets settled in one console.": "Onboarding, Verkauf und Abrechnung in einer Konsole.",
    "Finance team": "Finanzteam",
    "Reconciles every brand in a single ledger.": "Gleicht jede Marke in einem einzigen Hauptbuch ab.",
    "Each platform integrates Stripe, Adyen or a local acquirer directly, then builds escrow, split payouts and reconciliation itself. Rewards and loyalty run on entirely separate systems with no shared ledger.": "Jede Plattform integriert Stripe, Adyen oder einen lokalen Acquirer direkt und baut dann Treuhandlösungen, Split-Auszahlungen und den Abgleich selbst auf. Prämien- und Treuesysteme laufen auf völlig separaten Systemen ohne gemeinsames Hauptbuch.",
    "Regulatory licensing": "Regulatorische Zulassung",
    "Operate as a technical layer on partnered licensed institutions (e-money and acquiring) rather than holding funds ourselves at launch.": "Agieren zum Start als technische Schicht über lizenzierten Partnerinstituten (E-Geld und Acquiring), anstatt selbst Gelder zu halten.",
    "Concentration risk on one acquirer": "Konzentrationsrisiko bei einem Acquirer",
    "Multi-acquirer routing with automatic failover.": "Multi-Acquirer-Routing mit automatischem Failover.",
    "Stripe Connect": "Stripe Connect",
    "Best-in-class developer experience and coverage": "Erstklassige Developer Experience und Abdeckung",
    "We ride on licensed rails but add escrow, rewards issuing and group-level reconciliation; internally we capture the margin Stripe would keep": "Wir nutzen lizenzierte Infrastrukturen, ergänzen diese jedoch um Treuhandkonten, Prämienausgabe und Abgleich auf Konzernebene; intern behalten wir die Marge, die Stripe einbehalten würde",
    "Adyen for Platforms": "Adyen for Platforms",
    "Enterprise scale and unified commerce": "Enterprise-Skalierbarkeit und Unified Commerce",
    "Faster onboarding for small marketplaces and vertical features (milestone escrow, rewards) that enterprise processors treat as custom work": "Schnelleres Onboarding für kleine Marktplätze und vertikale Funktionen (Meilenstein-Treuhand, Prämien), die von Enterprise-Prozessoren als Individualentwicklung behandelt werden",
    "merchants, marketplaces and platform partners": "Händler, Marktplätze und Plattformpartner",
    "business subscription and payment-service contract": "Geschäftsabonnement und Zahlungsdienstleistungsvertrag",
    "Own-branded ordering storefront and app": "Bestell-Storefront und App im eigenen Branding",
    "0% order commission, flat daily fee": "0 % Bestellprovision, pauschale Tagesgebühr",
    "EPOS till with receipt printing": "EPOS-Kasse mit Quittungsdruck",
    "Kitchen display system (KDS)": "Küchendisplaysystem (KDS)",
    "Self-order kiosk mode": "Self-Order-Kiosk-Modus",
    "QR dine-in ordering and pay at table": "QR-Bestellung vor Ort und Bezahlen am Tisch",
    "Own drivers plus our driver network": "Eigene Fahrer plus unser Fahrernetzwerk",
    "ONYNGO Mix — bundled multi-vendor delivery": "ONYNGO Mix — gebündelte Lieferung von mehreren Anbietern",
    "Loyalty, promo codes and winback campaigns": "Loyalität, Aktionscodes und Rückgewinnungskampagnen",
    "Wholesale supplier catalogues and ordering": "Großhandelskataloge und Bestellung",
    "Live payouts and settlement dashboard": "Live-Auszahlungen und Abrechnungs-Dashboard",
    "Grocery and pharmacy catalogue management": "Katalogverwaltung für Lebensmittel und Apotheken",
    "Customers and delivery drivers are not charged an Onyngo platform subscription": "Kunden und Zusteller zahlen kein Onyngo-Plattform-Abonnement",
    "Customer ordering storefront": "Kunden-Bestell-Storefront",
    "Ordering, rewards and tracking": "Bestellung, Prämien und Tracking",
    "EPOS, KDS and kiosk for sites": "EPOS, KDS und Kiosk für Standorte",
    "Driver dispatch and proof of delivery": "Fahrerdisposition und Zustellnachweis",
    "Wholesale supplier catalogues and invoices": "Großhandelskataloge und Rechnungen",
    "Onboarding, payouts and moderation": "Onboarding, Auszahlungen und Moderation",
    "Independent takeaway": "Unabhängiger Imbiss",
    "Moves repeat customers off marketplaces and keeps 100% of the basket.": "Leitet Stammkunden von Marktplätzen weg und behält 100 % des Warenkorbwerts.",
    "Restaurant with dine-in": "Restaurant mit Vor-Ort-Verzehr",
    "Runs QR table ordering, kiosk and kitchen display on one till.": "Betreibt QR-Tischbestellung, Kiosk und Küchendisplay über eine Kasse.",
    "Grocery shop or pharmacy": "Lebensmittelgeschäft oder Apotheke",
    "Lists a full catalogue with stock tracking and local delivery.": "Listet einen vollständigen Katalog mit Bestandsverfolgung und lokaler Lieferung.",
    "Wholesale supplier": "Großhändler",
    "Takes trade orders and invoices from local sites commission-free.": "Nimmt Handelsaufträge und Rechnungen von lokalen Standorten provisionsfrei entgegen.",
    "Delivery driver": "Lieferfahrer",
    "Picks up batched local jobs with transparent per-drop pay.": "Übernimmt gebündelte lokale Aufträge mit transparenter Bezahlung pro Zustellung.",
    "Independent sites list on Just Eat, Uber Eats and Deliveroo at 14–30% commission, then buy a separate EPOS, kitchen display, kiosk and loyalty tool. They never own the customer record, so every repeat order is charged again.": "Unabhängige Standorte listen auf Just Eat, Uber Eats und Deliveroo gegen 14–30 % Provision und kaufen dann separate Tools für EPOS, Küchendisplay, Kiosk und Loyalität. Sie besitzen nie den Kundendatensatz, sodass jede Folgebestellung erneut berechnet wird.",
    "≈60,000 takeaways and ≈150,000 hospitality sites; ≈25m UK adults order food online.": "≈60.000 Imbisse und ≈150.000 Gastronomiebetriebe; ≈25 Mio. Erwachsene im Vereinigten Königreich bestellen online Essen.",
    "Consumer demand generation is harder without a marketplace brand": "Generierung von Endkundennachfrage ist ohne eine Marktplatzmarke schwieriger",
    "Demand is seeded from each site's existing customer base, QR table traffic and group cross-promotion, so orders do not depend on us buying category-level demand.": "Die Nachfrage wird aus dem bestehenden Kundenstamm jedes Standorts, dem QR-Tischverkehr und der gruppeninternen Cross-Promotion generiert, sodass Bestellungen nicht davon abhängen, dass wir Nachfrage auf Kategorieebene einkaufen.",
    "Driver supply in quiet areas": "Verfügbarkeit von Fahrern in ruhigen Gebieten",
    "Hybrid model: sites can use their own drivers, and ONYNGO Mix batches nearby drops to keep driver earnings viability.": "Hybridmodell: Standorte können eigene Fahrer nutzen, und ONYNGO Mix bündelt nahegelegene Zustellungen, um den Verdienst der Fahrer rentabel zu halten.",
    "Just Eat": "Just Eat",
    "Huge consumer demand and brand recall": "Enorme Kundennachfrage und Markenbekanntheit",
    "We charge 0% commission versus 14%+ and give the operator the customer data, so their repeat orders stop being rented": "Wir berechnen 0 % Provision statt 14 %+ und geben dem Betreiber die Kundendaten, damit Folgebestellungen nicht mehr „gemietet“ werden müssen",
    "Uber Eats / Deliveroo": "Uber Eats / Deliveroo",
    "Fast logistics network and app scale": "Schnelles Logistiknetzwerk und App-Skalierbarkeit",
    "Operators can use their own drivers or ours, keep the margin, and get EPOS, KDS and kiosk bundled instead of paying 30% plus four software subscriptions": "Betreiber können eigene oder unsere Fahrer nutzen, die Marge behalten und erhalten EPOS, KDS und Kiosk im Paket, anstatt 30 % plus vier Software-Abonnements zu zahlen",
    "Square / Lightspeed EPOS": "Square / Lightspeed EPOS",
    "Mature till hardware and payments": "Ausgereifte Kassenhardware und Zahlungen",
    "One flat daily fee covers ordering, till, KDS, kiosk and delivery together rather than per-module pricing": "Eine pauschale Tagesgebühr deckt Bestellung, Kasse, KDS, Kiosk und Lieferung zusammen ab, anstatt eine Abrechnung pro Modul vorzunehmen",
    "restaurants, retailers, pharmacies and other merchants": "Restaurants, Einzelhändler, Apotheken und andere Händler",
    "merchant subscription by location and enabled modules": "Händler-Abonnement nach Standort und aktivierten Modulen",
    "Room-level tenancies and rent ledgers": "Mietverhältnisse auf Zimmerebene und Mietbücher",
    "Applications, referencing and guarantors": "Bewerbungen, Referenzprüfung und Bürgen",
    "Deposit registration and move-out deductions": "Kautionsregistrierung und Abzüge beim Auszug",
    "Automated arrears chasing and payment plans": "Automatisierte Mahnung von Rückständen und Zahlungspläne",
    "HMO licence, EPC, gas and fire-safety calendar": "HMO-Lizenz, Energieausweis (EPC), Gas- und Brandschutzkalender",
    "Inspection scheduler with photo evidence": "Inspektionsplaner mit Fotonachweis",
    "Maintenance jobs and contractor assignment": "Wartungsaufträge und Beauftragung von Dienstleistern",
    "Notices and document templates": "Kündigungen und Dokumentenvorlagen",
    "Head-landlord splits for rent-to-rent deals": "Splits für Hauptvermieter bei Rent-to-Rent-Deals",
    "Banking reconciliation and expenses": "Bankabgleich und Ausgaben",
    "Room marketplace and public listings": "Zimmermarktplatz und öffentliche Inserate",
    "Full audit log and analytics": "Vollständiges Audit-Log und Analysen",
    "Tenants and guarantors use their portal free": "Mieter und Bürgen nutzen ihr Portal kostenlos",
    "Portfolio, tenancies, rent and compliance": "Portfolio, Mietverhältnisse, Miete und Compliance",
    "Apply, pay rent, report issues": "Bewerben, Miete zahlen, Probleme melden",
    "On-site inspections and photo evidence": "Vor-Ort-Inspektionen und Fotonachweis",
    "Public room listings and applications": "Öffentliche Zimmerinserate und Bewerbungen",
    "Agency accounts, audit and reporting": "Agenturkonten, Audit und Reporting",
    "HMO landlord": "HMO-Vermieter",
    "Runs twelve rooms across three houses with per-room arrears visibility.": "Betreibt zwölf Zimmer in drei Häusern mit Sichtbarkeit von Rückständen pro Zimmer.",
    "Rent-to-rent operator": "Rent-to-Rent-Betreiber",
    "Tracks head-landlord rent out, tenant rent in and the margin per property.": "Verfolgt die Mietzahlung an den Hauptvermieter, die Mieteinnahmen vom Mieter und die Marge pro Immobilie.",
    "Letting agency": "Vermietungsagentur",
    "Manages client portfolios with compliance evidence packs per property.": "Verwaltet Kundenportfolios mit Compliance-Nachweispaketen pro Immobilie.",
    "Applies, signs, pays rent and reports maintenance in one place.": "Bewerben, Unterschreiben, Miete zahlen und Wartung melden an einem Ort.",
    "Receives jobs, uploads before-and-after photos, gets paid.": "Erhält Aufträge, lädt Vorher-Nachher-Fotos hoch, wird bezahlt.",
    "HMO operators combine spreadsheets, WhatsApp, a bank app and generic landlord software that assumes one tenancy per property. Compliance dates live in personal calendars and evidence is reassembled by hand when a council inspects.": "HMO-Betreiber kombinieren Tabellenkalkulationen, WhatsApp, eine Bank-App und allgemeine Vermieter-Software, die von einem Mietverhältnis pro Immobilie ausgeht. Compliance-Termine stehen in persönlichen Kalendern und Nachweise werden bei einer Behördenprüfung manuell zusammengestellt.",
    "≈510,000 HMOs; ≈2.2m private landlords and ≈16,000 letting agency branches.": "≈510.000 HMOs; ≈2,2 Mio. private Vermieter und ≈16.000 Filialen von Vermietungsagenturen.",
    "Regulatory change across councils": "Regulatorische Änderungen in den Kommunen",
    "Licence conditions are configuration, not code, so per-council schemes and Wales/Scotland variations are updated as data.": "Lizenzbedingungen sind Konfiguration, kein Code, sodass kommunale Regelungen und Variationen für Wales/Schottland als Daten aktualisiert werden.",
    "Client money handling expectations": "Erwartungen an den Umgang mit Client Money",
    "Rent flows through regulated payment partners with client-money segregation; we never hold funds ourselves.": "Mietzahlungen fließen über regulierte Zahlungspartner mit Trennung von Kundengeldern; wir halten selbst niemals Gelder.",
    "Arthur Online": "Arthur Online",
    "Established lettings platform with integrations": "Etablierte Vermietungsplattform mit Integrationen",
    "Built room-first rather than property-first, with HMO licensing, fire safety and rent-to-rent head-landlord splits as native objects instead of workarounds": "„Room-first“ statt „Property-first“ konzipiert, mit HMO-Lizenzierung, Brandschutz und Rent-to-Rent-Splits für Hauptvermieter als native Objekte statt Workarounds",
    "Alto / Reapit": "Alto / Reapit",
    "Deep agency workflows and market share": "Tiefe Agentur-Workflows und Marktanteil",
    "Priced for small operators, self-serve onboarding in a day, and no per-branch enterprise contract": "Preisgestaltung für kleine Betreiber, Self-Service-Onboarding an einem Tag und kein Enterprise-Vertrag pro Filiale",
    "Spreadsheets and Landlord Vision": "Tabellenkalkulationen und Landlord Vision",
    "Cheap and familiar": "Günstig und vertraut",
    "Automated compliance deadlines and arrears chasing prevent rent-repayment orders that dwarf the subscription cost": "Automatisierte Compliance-Fristen und Mahnungen verhindern Rückzahlungsanordnungen, die die Abonnementkosten bei weitem übersteigen",
    "HMO landlords, operators and letting agencies": "HMO-Vermieter, Betreiber und Vermietungsagenturen",
    "subscription by property or room count": "Abonnement nach Anzahl der Immobilien oder Zimmer",
    "AI emotional support chat with safety guardrails": "KI-Chat für emotionale Unterstützung mit Sicherheitsleitplanken",
    "Mood and nafs tracking with trends": "Stimmungs- und Nafs-Tracking mit Trends",
    "Dua library: Arabic, transliteration, 14 languages": "Dua-Bibliothek: Arabisch, Transliteration, 14 Sprachen",
    "Islamic mindfulness, breathwork and bedtime audio": "Islamische Achtsamkeit, Atemübungen und Einschlaf-Audio",
    "Journaling and guided reflections": "Journaling und geführte Reflexionen",
    "Qur'an reading, audio and learning paths": "Koran-Lesen, Audio und Lernpfade",
    "AI Surah/Ayah guidance finder": "KI-Finder für Suren-/Vers-Orientierung",
    "Guided duas and adhkar with audio": "Geführte Duas und Adhkar mit Audio",
    "Family sharing and invites": "Familienfreigabe und Einladungen",
    "Courses and academy content": "Kurse und Akademie-Inhalte",
    "Offline caching for low-bandwidth regions": "Offline-Caching für Regionen mit geringer Bandbreite",
    "Crisis signposting to local resources": "Krisenwegweiser zu lokalen Ressourcen",
    "Mosques, charities and community partners are not charged by Nafsi": "Moscheen, Wohltätigkeitsorganisationen und Gemeinschaftspartner werden von Nafsi nicht belastet",
    "Full companion app": "Vollständige Companion-App",
    "Reading, journaling and account management": "Lesen, Journaling und Kontoverwaltung",
    "Content review, audio pipeline and moderation": "Inhaltsprüfung, Audio-Pipeline und Moderation",
    "Young adult": "Junger Erwachsener",
    "Uses AI chat and journaling during anxiety or low mood.": "Nutzt KI-Chat und Journaling bei Angstzuständen oder gedrückter Stimmung.",
    "Shares bedtime audio and duas with children via family sharing.": "Teilt Einschlaf-Audio und Duas mit Kindern über die Familienfreigabe.",
    "Revert or new learner": "Konvertit oder Neuling",
    "Follows guided Qur'an and adhkar learning paths.": "Folgt geführten Lernpfaden für Koran und Adhkar.",
    "Diaspora user": "Diaspora-Nutzer",
    "Reads duas in Urdu, Turkish or Bahasa alongside Arabic.": "Liest Duas auf Urdu, Türkisch oder Bahasa neben Arabisch.",
    "Grieving user": "Trauernder Nutzer",
    "Uses grief support flows and funeral-rites guidance.": "Nutzt Abläufe zur Trauerunterstützung und Anleitungen zu Bestattungsriten.",
    "Users juggle a prayer-time app, a separate Qur'an app and a Western wellbeing app that ignores faith. Emotional support is largely informal — family, WhatsApp groups or nothing — and paid wellbeing apps are priced out of most Muslim-majority markets.": "Nutzer jonglieren mit einer Gebetszeiten-App, einer separaten Koran-App und einer westlichen Wellbeing-App, die den Glauben ignoriert. Emotionale Unterstützung ist weitgehend informell — Familie, WhatsApp-Gruppen oder gar nichts — und kostenpflichtige Wellbeing-Apps sind für die meisten muslimisch geprägten Märkte zu teuer.",
    "≈2bn Muslims; ≈100m+ installs across the leading Islamic apps.": "≈2 Mrd. Muslime; ≈100 Mio.+ Installationen über die führenden islamischen Apps hinweg.",
    "Religious sensitivity and AI accuracy": "Religiöse Sensibilität und KI-Genauigkeit",
    "Strict scope: no fatwas, rulings, medical or therapy advice; scholar-reviewed content library and refusal guardrails in the AI layer.": "Strikter Umfang: keine Fatwas, Urteile, medizinischen oder therapeutischen Ratschläge; von Gelehrten geprüfte Inhaltsbibliothek und Ablehnungs-Leitplanken in der KI-Ebene.",
    "Very low ARPU": "Sehr niedriger ARPU",
    "Costs are dominated by shared group infrastructure; volume pricing plus family plans and later premium tiers lift revenue per household.": "Die Kosten werden durch die gemeinsam genutzte Konzerninfrastruktur dominiert; Mengenstaffelpreise plus Familientarife und spätere Premium-Stufen steigern den Umsatz pro Haushalt.",
    "Muslim Pro": "Muslim Pro",
    "Enormous installed base and prayer-time habit": "Enorme installierte Basis und Gebetszeit-Gewohnheit",
    "We lead with emotional wellbeing and AI reflection rather than utility features, and charge a tiny yearly fee instead of heavy ad monetisation": "Wir setzen auf emotionales Wohlbefinden und KI-Reflexion statt auf Utility-Features und erheben eine geringe Jahresgebühr statt starker Anzeigenmonetisierung",
    "Calm / Headspace": "Calm / Headspace",
    "Premium production and brand": "Premium-Produktion und -Marke",
    "Faith-native content in 14 languages at a fraction of the price, in markets their pricing excludes entirely": "Glaubensnahe Inhalte in 14 Sprachen zu einem Bruchteil des Preises, in Märkten, die durch deren Preisgestaltung völlig ausgeschlossen werden",
    "Quran apps (Tarteel, Quran.com)": "Koran-Apps (Tarteel, Quran.com)",
    "Deep recitation and memorisation tooling": "Umfangreiche Rezitations- und Memorierungstools",
    "We combine Qur'an guidance with mood tracking, duas and mindfulness in one companion rather than a single-purpose tool": "Wir kombinieren Koran-Orientierung mit Stimmungs-Tracking, Duas und Achtsamkeit in einem Begleiter statt eines Einzelzweck-Tools",
    "individuals and families choosing the premium wellbeing plan": "Einzelpersonen und Familien, die sich für den Premium-Wellbeing-Plan entscheiden",
    "low-cost individual or family subscription": "kostengünstiges Einzel- oder Familienabonnement",
    "Paying individual or family accounts": "Zahlende Einzel- oder Familienkonten",
    "SFBB-aligned daily and weekly check diaries": "SFBB-konforme tägliche und wöchentliche Kontrolltagebücher",
    "Bluetooth probe and fridge sensor logging": "Bluetooth-Sonde und Kühlsensor-Protokollierung",
    "Natasha's Law allergen matrices from recipes": "Allergenmatrizen nach Natasha's Law aus Rezepten",
    "Cleaning schedules with photo evidence": "Reinigungspläne mit Fotonachweis",
    "Delivery and supplier acceptance checks": "Liefer- und Lieferantenannahmeprüfungen",
    "Corrective actions with escalation alerts": "Korrekturmaßnahmen mit Eskalationsalarmen",
    "Staff training records and sign-off": "Schulungsunterlagen und Abzeichnung durch das Personal",
    "Multi-site dashboard with hygiene risk scoring": "Multi-Standort-Dashboard mit Hygiene-Risikobewertung",
    "One-tap inspection evidence pack (PDF)": "Ein-Klick-Inspektionsnachweispaket (PDF)",
    "EPOS and rota integrations": "EPOS- und Dienstplan-Integrationen",
    "Staff use the checks under the site's account": "Mitarbeiter nutzen die Kontrollen unter dem Konto des Standorts",
    "Owner and multi-site compliance dashboard": "Compliance-Dashboard für Eigentümer und mehrere Standorte",
    "Internal ops and support console": "Interne Betriebs- und Supportkonsole",
    "Independent owner": "Unabhängiger Eigentümer",
    "Checks all sites are compliant from a phone before opening.": "Prüft vor der Öffnung per Telefon, ob alle Standorte compliant sind."
}

with open('/tmp/tr5.json', 'r') as f:
    original_keys = json.load(f)

result = {}
missing = []
for key in original_keys:
    if key in translations:
        result[key] = translations[key]
    else:
        missing.append(key)
        result[key] = key

if missing:
    print(f"Missing translations for: {missing}")

with open('/tmp/de5.json', 'w') as f:
    json.dump(result, f, ensure_ascii=False, indent=2)
