const fs = require('fs');

const input = JSON.parse(fs.readFileSync('/tmp/chunk0.json', 'utf8'));

const translations = {
  "Experten finden. Sicher entscheiden.": "Experten finden. Sicher entscheiden.",
  "Immobilien. Einfach geregelt.": "Immobilien. Einfach geregelt.",
  "The complete AI business operating system.": "Das vollständige KI-Betriebssystem für Unternehmen.",
  "Omniqora is the complete AI business operating system — sold as Omniqora One with six modules (Connect, Voice, Flow, Agents, Exchange and the Qora assistant) on one login and one bill. At its core is the omnichannel customer-conversation engine: WhatsApp, Instagram, Messenger, SMS, e-mail, web-chat, Telegram and voice land in one team inbox, and every conversation becomes a case with qualification, appointment, document request, quote, payment, third-party fulfilment and follow-up. One engine sold three ways — embedded add-on inside any iTechLounge brand, standalone SaaS for independent SMEs, and a partner/white-label edition for agencies, groups and resellers. No commission on anything our customers earn: flat regional subscriptions plus transparent pass-through of channel, model and payment-provider fees.": "Omniqora ist das vollständige KI-Betriebssystem für Unternehmen – verkauft als Omniqora One mit sechs Modulen (Connect, Voice, Flow, Agents, Exchange und der Qora-Assistent) mit einem Login und einer Rechnung. Das Herzstück ist die Omnichannel-Engine für Kundeninteraktionen: WhatsApp, Instagram, Messenger, SMS, E-Mail, Web-Chat, Telegram und Telefonie landen in einem gemeinsamen Team-Posteingang. Jedes Gespräch wird zu einem Fall mit Qualifizierung, Termin, Dokumentenanforderung, Angebot, Zahlung, Abwicklung durch Drittanbieter und Follow-up. Eine Engine, drei Vertriebswege – als eingebettetes Add-on innerhalb jeder iTechLounge-Marke, als eigenständiges SaaS für unabhängige KMU und als Partner-/White-Label-Edition für Agenturen, Gruppen und Wiederverkäufer. Keine Provision auf die Einnahmen unserer Kunden: pauschale regionale Abonnements plus transparente Weitergabe von Kanal-, Modell- und Zahlungsanbieter-Gebühren.",
  "Verified car marketplace for the UK": "Verifizierter Automarktplatz für Großbritannien",
  "UK sister marketplace to ZIVVO Germany: verified private and dealer car listings with HPI, MOT and finance checks, escrow payments and delivery. Same engine, UK compliance and pricing.": "Britisches Schwester-Portal zu ZIVVO Deutschland: verifizierte Fahrzeuginserate von Privatpersonen und Händlern mit HPI-, MOT- und Finanzierungsprüfungen, Treuhandzahlungen und Lieferung. Gleiche Engine, britische Compliance und Preisgestaltung.",
  "≈7.2m used-car transactions per year in the UK; ≈£1.1bn spent on listings, leads and dealer software.": "≈7,2 Mio. Gebrauchtwagentransaktionen pro Jahr in Großbritannien; ≈1,1 Mrd. £ Ausgaben für Inserate, Leads und Händlersoftware.",
  "Independent dealers, franchise groups, private sellers, car buyers.": "Unabhängige Händler, Franchise-Gruppen, private Verkäufer, Autokäufer.",
  "UK dealers pay Auto Trader £1,000–£3,000 per month per forecourt for listings alone and still handle checks, payments and delivery off-platform. ZIVVO UK bundles listing, HPI/MOT verification, escrow and delivery into one subscription at a fraction of the cost.": "Britische Händler zahlen Auto Trader 1.000–3.000 £ pro Monat und Standort allein für Inserate und müssen Prüfungen, Zahlungen und Lieferung dennoch außerhalb der Plattform abwickeln. ZIVVO UK bündelt Inserat, HPI/MOT-Verifizierung, Treuhandservice und Lieferung in einem Abonnement zu einem Bruchteil der Kosten.",
  "One subscription puts a dealer's whole stock online with automatic HPI, MOT-history and mileage verification, finance quotes, escrow-protected payment and nationwide delivery booking — no per-lead fees, no upsells.": "Ein Abonnement bringt den gesamten Bestand eines Händlers online mit automatischer HPI-, MOT-Historie- und Kilometerstands-Verifizierung, Finanzierungsangeboten, treuhandgesicherten Zahlungen und landesweiter Lieferungsbuchung – keine Gebühren pro Lead, kein Upselling.",
  "Childminder agency & childcare software for the UK": "Tagesmütter-Agentur & Kinderbetreuungs-Software für Großbritannien",
  "UK childminder agency and directory: parents search vetted, Ofsted-registered childminders by postcode; providers get bookings, registers, invoicing and compliance packs. Agency model lets us register childminders under our own umbrella.": "Britische Tagesmütter-Agentur und Verzeichnis: Eltern suchen geprüfte, bei Ofsted registrierte Tagesmütter nach Postleitzahl; Anbieter erhalten Buchungen, Register, Rechnungsstellung und Compliance-Pakete. Das Agenturmodell ermöglicht es uns, Tagesmütter unter unserem eigenen Dach zu registrieren.",
  "≈4.7m children under 9 in England; ≈£7.6bn annual childcare spend; ≈27,000 registered childminders.": "≈4,7 Mio. Kinder unter 9 Jahren in England; ≈7,6 Mrd. £ jährliche Ausgaben für Kinderbetreuung; ≈27.000 registrierte Tagesmütter.",
  "Working parents, childminders, nurseries, employers offering childcare benefits.": "Berufstätige Eltern, Tagesmütter, Kindergärten, Arbeitgeber, die Kinderbetreuungsleistungen anbieten.",
  "England lost over 12,000 childminders in five years, largely to paperwork and Ofsted burden. As a registered childminder agency we absorb registration, inspection and compliance so carers can work — and parents get vetted care with one search.": "England hat in fünf Jahren über 12.000 Tagesmütter verloren, größtenteils aufgrund von Papierkram und der Ofsted-Belastung. Als registrierte Tagesmütter-Agentur übernehmen wir Registrierung, Inspektion und Compliance, damit die Betreuer arbeiten können – und Eltern erhalten mit einer Suche geprüfte Betreuung.",
  "Two products in one: a consumer directory with postcode search, availability and instant booking, and an agency SaaS giving childminders registration, DBS tracking, EYFS learning journals, invoicing and Tax-Free Childcare handling for a flat monthly fee.": "Zwei Produkte in einem: ein Endkunden-Verzeichnis mit Postleitzahlensuche, Verfügbarkeit und Sofortbuchung sowie ein Agentur-SaaS, das Tagesmüttern Registrierung, DBS-Tracking, EYFS-Lerntagebücher, Rechnungsstellung und die Abwicklung der steuerfreien Kinderbetreuung für eine monatliche Pauschale bietet.",
  "Find and compare UK accountants — free": "Britische Buchhalter finden und vergleichen – kostenlos",
  "A matching marketplace where businesses describe their needs and receive vetted, fixed-price quotes from UK accountants. Transparent pricing, verified ICAEW/ACCA credentials, and reviews from real clients.": "Ein Matching-Marktplatz, auf dem Unternehmen ihren Bedarf beschreiben und geprüfte Festpreisangebote von britischen Buchhaltern erhalten. Transparente Preise, verifizierte ICAEW/ACCA-Referenzen und Bewertungen von echten Kunden.",
  "≈5.6m UK businesses; ≈£12bn spent annually on accountancy and bookkeeping.": "≈5,6 Mio. britische Unternehmen; ≈12 Mrd. £ jährliche Ausgaben für Buchhaltung und Buchführung.",
  "Sole traders, limited-company directors, landlords, small practices seeking clients.": "Einzelunternehmer, Geschäftsführer von Limited-Gesellschaften, Vermieter, kleine Kanzleien auf Kundensuche.",
  "Choosing an accountant is opaque: no published prices, no verified credentials, and referral sites simply sell the same lead to five firms. TAXNUVIA publishes fixed prices and verifies every practice.": "Die Auswahl eines Buchhalters ist intransparent: keine veröffentlichten Preise, keine verifizierten Referenzen, und Vermittlungsseiten verkaufen denselben Lead einfach an fünf Firmen. TAXNUVIA veröffentlicht Festpreise und verifiziert jede Kanzlei.",
  "Free for the business: answer 8 questions, get 3 verified fixed-price quotes within 24 hours. Accountants pay a subscription for verified-practice status plus a success fee on won clients — no blind lead-selling.": "Kostenlos für das Unternehmen: 8 Fragen beantworten, 3 verifizierte Festpreisangebote innerhalb von 24 Stunden erhalten. Buchhalter zahlen ein Abonnement für den Status als verifizierte Kanzlei plus eine Erfolgsprovision für gewonnene Kunden – kein blinder Lead-Verkauf.",
  "The property OS for UK agencies and landlords": "Das Immobilien-Betriebssystem für britische Agenturen und Vermieter",
  "A public property marketplace fused with a full agency CRM, compliance hub and tenant portal — sales, lettings, HMO and commercial in one workspace.": "Ein öffentlicher Immobilienmarktplatz verschmolzen mit einem vollständigen Agentur-CRM, Compliance-Hub und Mieterportal – Verkauf, Vermietung, HMO und Gewerbe in einem Arbeitsbereich.",
  "≈25,000 UK estate and letting agency branches; ≈£2.4bn spent on portals and agency software.": "≈25.000 britische Immobilien- und Vermietungsagentur-Filialen; ≈2,4 Mrd. £ Ausgaben für Portale und Agentursoftware.",
  "Estate agents, letting agents, landlords, tenants, buyers.": "Immobilienmakler, Vermietungsagenten, Vermieter, Mieter, Käufer.",
  "Agents pay Rightmove and Zoopla thousands a month for listings, then pay again for a CRM (Reapit, Alto), again for compliance (Goodlord) and again for tenant referencing. GABLEY is one system at one price.": "Agenten zahlen Rightmove und Zoopla Tausende pro Monat für Inserate, dann erneut für ein CRM (Reapit, Alto), erneut für Compliance (Goodlord) und erneut für die Mieterreferenzierung. GABLEY ist ein System zu einem Preis.",
  "Marketplace exposure, CRM, compliance and tenant portal in a single subscription — with portal syndication included — cutting an average branch's software and listing bill by more than half.": "Marktplatz-Präsenz, CRM, Compliance und Mieterportal in einem einzigen Abonnement – inklusive Portal-Syndizierung – reduziert die Software- und Inseratskosten einer durchschnittlichen Filiale um mehr als die Hälfte.",
  "Salon booking & management software": "Salon-Buchungs- & Management-Software",
  "Consumer booking marketplace plus full salon management: calendar, staff rotas, stock, payments and marketing for hair, beauty and barber businesses.": "Endkunden-Buchungsmarktplatz plus vollständiges Salon-Management: Kalender, Dienstpläne, Lagerbestand, Zahlungen und Marketing für Friseur-, Beauty- und Barbershops.",
  "≈45,000 UK hair and beauty businesses; ≈£8.5bn consumer spend.": "≈45.000 britische Friseur- und Beauty-Unternehmen; ≈8,5 Mrd. £ Konsumausgaben.",
  "Salon owners, independent stylists, barbers, beauty therapists, clients.": "Salonbesitzer, unabhängige Stylisten, Barbiere, Kosmetiker, Kunden.",
  "Salons lose 15-20% of revenue to no-shows and pay marketplaces up to £3 per new-client booking on top of a monthly fee. STYLESYNC charges one flat subscription with zero commission on bookings.": "Salons verlieren 15–20 % ihres Umsatzes durch Nichterscheinen und zahlen Marktplätzen zusätzlich zu einer monatliche Gebühr bis zu 3 £ pro Neukundenbuchung. STYLESYNC berechnet ein pauschales Abonnement ohne Provision auf Buchungen.",
  "Everything a salon needs — online booking, deposits that kill no-shows, rotas, stock, card payments and automated rebooking marketing — for a flat monthly fee with no per-booking commission, plus free exposure on the consumer marketplace.": "Alles, was ein Salon braucht – Online-Buchung, Anzahlungen gegen Nichterscheinen, Dienstpläne, Lagerbestand, Kartenzahlungen und automatisiertes Rebooking-Marketing – für eine monatliche Pauschale ohne Provision pro Buchung, plus kostenlose Präsenz auf dem Endkunden-Marktplatz.",
  "AI recruitment for engineering, medical, law and finance": "KI-Personalvermittlung für Technik, Medizin, Recht und Finanzen",
  "Specialist AI-matched job platform for regulated and technical professions: CV parsing, skills matching, compliance-document tracking and interview scheduling for candidates and employers.": "Spezialisierte KI-gestützte Jobplattform für reglementierte und technische Berufe: CV-Parsing, Skill-Matching, Tracking von Compliance-Dokumenten und Terminplanung für Vorstellungsgespräche für Bewerber und Arbeitgeber.",
  "≈£43bn UK recruitment market; professional/technical niches account for ≈£12bn.": "≈43 Mrd. £ britischer Personalvermittlungsmarkt; professionelle/technische Nischen machen ≈12 Mrd. £ aus.",
  "Engineers, clinicians, solicitors, finance professionals, employers, agencies.": "Ingenieure, Kliniker, Anwälte, Finanzexperten, Arbeitgeber, Agenturen.",
  "Agencies charge 15-25% of first-year salary — £9,000+ on a £45k engineer — for a process that is largely CV matching and diary management. XPERTJOBS does the matching with AI and charges a subscription.": "Agenturen berechnen 15–25 % des ersten Jahresgehalts – über 9.000 £ bei einem Ingenieur mit 45.000 £ Gehalt – für einen Prozess, der größtenteils aus CV-Matching und Terminverwaltung besteht. XPERTJOBS übernimmt das Matching per KI und berechnet ein Abonnement.",
  "Employers pay a flat monthly subscription for unlimited hires: AI shortlists from a verified, credential-checked talent pool, tracks GMC/NMC/SRA/CEng registrations and expiry, and books interviews automatically. Typical saving versus agency fees exceeds 80%.": "Arbeitgeber zahlen ein pauschales monatliches Abonnement für unbegrenzte Einstellungen: KI erstellt Shortlists aus einem verifizierten, geprüften Talent-Pool, verfolgt GMC/NMC/SRA/CEng-Registrierungen und deren Ablauf und bucht Interviews automatisch. Die typische Ersparnis gegenüber Agenturgebühren liegt bei über 80 %.",
  "Jobs, materials and delivery for UK trades": "Aufträge, Material und Lieferung für das britische Handwerk",
  "Three-sided platform connecting tradespeople, customers and drivers: job management and quoting, materials ordering at trade prices, and same-day delivery to site.": "Dreiseitige Plattform, die Handwerker, Kunden und Fahrer verbindet: Auftragsmanagement und Angebotserstellung, Materialbestellung zu Fachhandelspreisen und Lieferung am selben Tag zur Baustelle.",
  "≈900,000 UK trade businesses; ≈£29bn annual builders'-merchant spend.": "≈900.000 britische Handwerksbetriebe; ≈29 Mrd. £ jährliche Ausgaben bei Baustoffhändlern.",
  "Electricians, plumbers, builders, homeowners, merchants, van drivers.": "Elektriker, Klempner, Bauunternehmer, Hausbesitzer, Händler, Transporterfahrer.",
  "A tradesperson loses roughly an hour a day driving to a merchant, quotes on scraps of paper, and chases invoices for weeks. TRADEROS puts the merchant, the paperwork and the delivery in the van's phone.": "Ein Handwerker verliert täglich etwa eine Stunde durch die Fahrt zum Händler, schreibt Angebote auf Zettel und läuft wochenlang Rechnungen hinterher. TRADEROS bringt den Händler, den Papierkram und die Lieferung auf das Smartphone im Transporter.",
  "Free job management (quotes, invoices, scheduling) funded by margin on materials and delivery: order at trade prices from partnered merchants, get it delivered to site within hours, and invoice the customer with materials auto-costed.": "Kostenloses Auftragsmanagement (Angebote, Rechnungen, Zeitplanung), finanziert durch die Marge auf Material und Lieferung: Bestellen Sie zu Fachhandelspreisen bei Partnervormärkten, lassen Sie sich die Ware innerhalb weniger Stunden auf die Baustelle liefern und stellen Sie dem Kunden die Rechnung mit automatisch kalkulierten Materialkosten.",
  "Gamified compliance training for care & education": "Gamifiziertes Compliance-Training für Pflege & Bildung",
  "Blended compliance training platform for CQC, Ofsted and Skills for Care providers: mandatory e-learning, practical sign-off, gamified progress and inspection-ready matrices.": "Blended-Compliance-Trainingsplattform für CQC-, Ofsted- und Skills for Care-Anbieter: verpflichtendes E-Learning, praktische Abnahme, gamifizierter Fortschritt und inspektionsbereite Matrizen.",
  "≈1.7m adult social care workers plus ≈600,000 early-years staff in England; ≈£900m training spend.": "≈1,7 Mio. Beschäftigte in der Erwachsenenpflege plus ≈600.000 Mitarbeiter im frühkindlichen Bereich in England; ≈900 Mio. £ Trainingsausgaben.",
  "Care providers, nurseries, training managers, care workers, apprentices.": "Pflegeanbieter, Kindergärten, Schulungsleiter, Pflegekräfte, Auszubildende.",
  "Mandatory training is the single most common CQC and Ofsted compliance gap, yet most providers track it on a spreadsheet and buy e-learning that staff click through without learning anything.": "Pflichtschulungen sind die häufigste Compliance-Lücke bei CQC und Ofsted, doch die meisten Anbieter verfolgen diese in einer Tabellenkalkulation und kaufen E-Learning-Kurse, die das Personal einfach durchklickt, ohne etwas zu lernen."
};

const output = {};
input.forEach(key => {
  if (translations[key]) {
    output[key] = translations[key];
  } else {
    console.error('Missing translation for:', key);
  }
});

fs.writeFileSync('/tmp/out0.json', JSON.stringify(output, null, 2));
