import json

data = json.load(open('/tmp/tr0.json'))

translations = {
    "Their staff use the checks under the site's account": "Deren Mitarbeiter nutzen die Checks über den Account des Standorts",
    "No second-side platform fee: we do not charge both the user side and the business side": "Keine zweiseitige Plattformgebühr: Wir erheben keine Gebühren sowohl auf der Nutzer- als auch auf der Geschäftsseite",
    "FoodNotify": "FoodNotify",
    "Flowtify": "Flowtify",
    "Optional onboarding, promotion or extra modules may be sold only to that same paying side": "Optionale Onboarding-, Promotion- oder Zusatzmodule werden ausschließlich an die jeweils zahlende Seite verkauft",
    "restaurants, hotels, caterers and food-service sites": "Restaurants, Hotels, Caterer und Gastronomiebetriebe",
    "subscription per operating site": "Abonnement pro Betriebsstandort",
    "Average revenue per paying business / month": "Durchschnittlicher Umsatz pro zahlendem Unternehmen / Monat",
    "Paying businesses cancelling each month": "Zahlende Unternehmen, die monatlich kündigen",
    "Kinderstars helps parents in Germany find and organise care with verified childminders. Registered childminders pay Kinderstars a monthly subscription for their profile, availability, bookings, attendance, invoices and records. Parents use Kinderstars free. The parent pays the childminder for the childcare itself, or an eligible government scheme funds the place, and the childminder receives that childcare payment.": "Kinderstars hilft Eltern in Deutschland dabei, Betreuung durch verifizierte Kindertagespflegepersonen zu finden und zu organisieren. Registrierte Kindertagespflegepersonen zahlen an Kinderstars ein monatliches Abonnement für Profil, Verfügbarkeit, Buchungen, Anwesenheit, Rechnungsstellung und Unterlagen. Eltern nutzen Kinderstars kostenlos. Die Eltern bezahlen die Kindertagespflegeperson für die Betreuung selbst, oder ein staatliches Förderprogramm finanziert den Platz, und die Kindertagespflegeperson erhält diese Zahlung.",
    "One clear money flow: the childminder pays Kinderstars a monthly software and marketplace subscription. Parents search, compare, book and receive records without a Kinderstars platform fee. The separate childcare charge is agreed with and paid to the childminder, either by the parent or through an eligible government funding route. Kinderstars helps the childminder manage availability, attendance, invoices and the evidence needed for funded places but does not take the childcare income.": "Ein klarer Geldfluss: Die Kindertagespflegeperson zahlt an Kinderstars ein monatliches Software- und Marktplatz-Abonnement. Eltern suchen, vergleichen, buchen und erhalten Unterlagen ohne eine Kinderstars-Plattformgebühr. Die separate Betreuungsgebühr wird mit der Kindertagespflegeperson vereinbart und an diese gezahlt, entweder durch die Eltern oder über einen staatlichen Förderweg. Kinderstars unterstützt die Kindertagespflegeperson bei der Verwaltung von Verfügbarkeit, Anwesenheit, Rechnungen und den für geförderte Plätze erforderlichen Nachweisen, nimmt jedoch keine Anteile an den Betreuungseinnahmen.",
    "Paying customers are registered childminders. Parents and families use the search and booking journey free; local authorities and government funding schemes may fund the childcare service but do not buy the Kinderstars software subscription.": "Zahlende Kunden sind registrierte Kindertagespflegepersonen. Eltern und Familien nutzen die Suche und den Buchungsprozess kostenlos; Kommunen und staatliche Förderprogramme finanzieren zwar gegebenenfalls die Betreuungsleistung, erwerben aber nicht das Kinderstars-Softwareabonnement.",
    "Parents search and organise care free; they pay the childminder for the childcare itself, or an eligible government scheme funds it, and that money goes to the childminder": "Eltern suchen und organisieren die Betreuung kostenlos; sie bezahlen die Kindertagespflegeperson für die Betreuung selbst, oder ein staatliches Programm finanziert diese, und das Geld geht direkt an die Kindertagespflegeperson",
    "Betreut.de": "Betreut.de",
    "registered childminders": "registrierte Kindertagespflegepersonen",
    "monthly childminder subscription": "monatliches Abonnement für Kindertagespflegepersonen",
    "Hosts plan free. Venues, suppliers and event agencies pay a flat monthly subscription for marketplace visibility, customer management, calendars, quotes, contracts and payments, and keep 100% of every booking. The host describes the event once, EventPlanr builds the task list, budget and supplier shortlist, collects comparable quotes, runs guest replies and seating, and gives everyone one shared event-day timeline. There is no host subscription, supplier commission or per-lead fee.": "Veranstalter planen kostenlos. Locations, Dienstleister und Event-Agenturen zahlen ein pauschales monatliches Abonnement für Marktplatz-Sichtbarkeit, Kundenmanagement, Kalender, Angebote, Verträge sowie Zahlungen und behalten 100 % jeder Buchung. Der Veranstalter beschreibt das Event einmal, EventPlanr erstellt die Aufgabenliste, das Budget sowie die Dienstleister-Shortlist, holt vergleichbare Angebote ein, verwaltet Gäste-Rückmeldungen sowie Sitzpläne und stellt allen Beteiligten einen gemeinsamen Zeitplan für den Veranstaltungstag zur Verfügung. Es gibt kein Abonnement für Veranstalter, keine Vermittlungsprovision und keine Gebühr pro Lead.",
    "Private and corporate hosts plan events and contact suppliers free": "Private und geschäftliche Veranstalter planen Events und kontaktieren Dienstleister kostenlos",
    "eventinc": "eventinc",
    "WeddyPlace / hochzeitsportal24": "WeddyPlace / hochzeitsportal24",
    "Cvent / Bizzabo": "Cvent / Bizzabo",
    "Excel + WhatsApp + Doodle": "Excel + WhatsApp + Doodle",
    "venues, suppliers and event agencies": "Locations, Dienstleister und Event-Agenturen",
    "subscription by supplier, venue or agency account": "Abonnement pro Dienstleister-, Location- oder Agentur-Account",
    "Food businesses publish surprise-bag inventory of surplus food and consumers discover and reserve it free. Rettio charges the merchant a flat monthly subscription and takes no fee from the consumer and no commission from the food sale.": "Lebensmittelbetriebe veröffentlichen Bestände an Überraschungstüten mit überschüssigen Lebensmitteln, die Konsumenten kostenlos entdecken und reservieren können. Rettio berechnet dem Händler ein pauschales monatliches Abonnement und erhebt keine Gebühren vom Konsumenten sowie keine Provision auf den Lebensmittelverkauf.",
    "Food merchants pay one flat subscription per location to publish unlimited surplus bags, receive direct payment and keep the customer relationship. Consumers search, reserve and collect without a Rettio membership or platform fee. The merchant keeps the full sale value apart from normal card-processing costs.": "Lebensmittelhändler zahlen ein Pauschal-Abonnement pro Standort, um unbegrenzt Tüten mit Überschüssen zu veröffentlichen, direkte Zahlungen zu erhalten und die Kundenbeziehung zu behalten. Konsumenten suchen, reservieren und holen ab, ohne eine Rettio-Mitgliedschaft oder Plattformgebühr. Der Händler behält den vollen Verkaufswert abzüglich normaler Kartenzahlungskosten.",
    "Consumers discover and reserve surplus food without a Rettio membership": "Konsumenten entdecken und reservieren überschüssige Lebensmittel ohne Rettio-Mitgliedschaft",
    "Too Good To Go": "Too Good To Go",
    "bakeries, cafés, supermarkets, hotels and other food merchants": "Bäckereien, Cafés, Supermärkte, Hotels und andere Lebensmittelhändler",
    "flat subscription per merchant location": "Pauschal-Abonnement pro Händlerstandort",
    "Residents, visitors and community users search free": "Anwohner, Besucher und Community-Nutzer suchen kostenlos",
    "Yelp": "Yelp",
    "TripAdvisor": "TripAdvisor",
    "local businesses that claim enhanced profiles or promotion": "Lokale Unternehmen, die erweiterte Profile oder Werbung buchen",
    "business profile and promotion subscription": "Abonnement für Unternehmensprofil und Werbung",
    "Lead marketplace: clients post a mandate, advisors buy or bid on matching leads": "Lead-Marktplatz: Mandanten veröffentlichen ein Mandat, Berater kaufen passende Leads oder bieten darauf",
    "Advisor CRM with pipeline, tasks, calendar and quote builder": "Berater-CRM mit Pipeline, Aufgaben, Kalender und Angebotserstellung",
    "City and service landing pages for local SEO": "Stadt- und Leistungs-Landingpages für lokales SEO",
    "Rechtstipps and resources content hub with expert articles": "Rechtstipps- und Ressourcen-Content-Hub mit Expertenartikeln",
    "Compare and search filters by profession, sector, city and language": "Vergleichs- und Suchfilter nach Beruf, Branche, Stadt und Sprache",
    "Verified reviews with published review and verification policies": "Verifizierte Bewertungen mit veröffentlichten Richtlinien zur Prüfung und Verifizierung",
    "Sales-agent portal with referrals, commissions and KPI tracking": "Portal für Vertriebsagenten mit Empfehlungen, Provisionen und KPI-Tracking",
    "Admin back office: verifications, complaints, sectors, reporting and audit log": "Admin-Backoffice: Verifizierungen, Beschwerden, Branchen, Reporting und Audit-Log",
    "People and businesses seeking advice submit and compare requests free": "Ratsuchende Personen und Unternehmen reichen Anfragen kostenlos ein und vergleichen diese",
    "Sales agent / partner": "Vertriebsagent / Partner",
    "Onboards advisors in their region and earns recurring commission.": "Führt Berater in ihrer Region ein und verdient wiederkehrende Provisionen.",
    "Platform admin": "Plattform-Admin",
    "Verifies credentials, handles complaints and monitors marketplace quality.": "Verifiziert Qualifikationen, bearbeitet Beschwerden und überwacht die Marktplatzqualität.",
    "anwalt.de": "anwalt.de",
    "law, tax, accounting and audit practices": "Kanzleien für Recht, Steuern, Buchhaltung und Wirtschaftsprüfung",
    "professional-practice subscription": "Abonnement für Kanzleien/Praxen",
    "Candidates search, match and apply free": "Kandidaten suchen, matchen und bewerben sich kostenlos",
    "StepStone": "StepStone",
    "employers and recruitment agencies": "Arbeitgeber und Personalvermittlungen",
    "employer subscription by hiring volume": "Arbeitgeber-Abonnement nach Einstellungsvolumen",
    "Passengers and corporate bookers are not charged a Viazeno service fee": "Fahrgäste und Firmenbucher zahlen keine Viazeno-Servicegebühr",
    "Blacklane": "Blacklane",
    "chauffeur and private-hire operators": "Chauffeur- und Mietwagenunternehmen",
    "operator subscription by vehicle or team size": "Betreiber-Abonnement nach Fahrzeug- oder Teamgröße",
    "Handwerker & Makler marketplace with verified profiles": "Handwerker- & Makler-Marktplatz mit verifizierten Profilen",
    "Instant property valuation (Bewertung) and Mietspiegel data": "Sofortige Immobilienbewertung und Mietspiegel-Daten",
    "Financing enquiries and Bonitäts-checks in one flow": "Finanzierungsanfragen und Bonitäts-Checks in einem Prozess",
    "Neighbourhood (Stadtteile) insights and landlord Ratgeber content": "Stadtteil-Insights und Ratgeber-Inhalte für Vermieter",
    "Tenants use their portal without a separate platform charge": "Mieter nutzen ihr Portal ohne separate Plattformgebühr",
    "ImmoScout24": "ImmoScout24",
    "landlords and property managers": "Vermieter und Hausverwaltungen",
    "subscription by managed property count": "Abonnement nach Anzahl verwalteter Immobilien",
    "Employees and their families use the included relocation support free": "Mitarbeiter und deren Familien nutzen die enthaltene Relocation-Unterstützung kostenlos",
    "Local charities & Behörden": "Lokale Hilfsorganisationen & Behörden",
    "employers relocating international staff": "Arbeitgeber, die internationales Personal umsiedeln",
    "employer subscription or relocation package": "Arbeitgeber-Abonnement oder Relocation-Paket",
    "Online academy delivering approved German-language and technology courses funded by German public programmes or employers. Eligible learners study without paying Traindirekt directly.": "Online-Akademie für zugelassene Deutsch- und Technologiekurse, die durch deutsche öffentliche Programme oder Arbeitgeber gefördert werden. Berechtigte Lernende nehmen teil, ohne direkt an Traindirekt zu zahlen.",
    "One academy with one paying side: the Agentur für Arbeit, Jobcenter, BAMF or an employer funds each eligible learner place. The learner pays no Traindirekt subscription. Courses combine live cohort sessions, on-demand video, AI tutors and recognised exam preparation, with attendance, outcomes and evidence reported back to the funding organisation.": "Eine Akademie mit einer zahlenden Seite: Die Agentur für Arbeit, das Jobcenter, das BAMF oder ein Arbeitgeber finanziert jeden berechtigten Teilnehmerplatz. Der Lernende zahlt kein Traindirekt-Abonnement. Die Kurse kombinieren Live-Kohortensitzungen, On-Demand-Videos, KI-Tutoren und anerkannte Prüfungsvorbereitung, wobei Anwesenheit, Ergebnisse und Nachweise an die fördernde Organisation zurückgemeldet werden.",
    "Eligible learners study without a Traindirekt subscription": "Berechtigte Lernende studieren ohne ein Traindirekt-Abonnement",
    "DeutschAkademie / Speexx / Lingoda": "DeutschAkademie / Speexx / Lingoda",
    "IU Akademie / WBS Training / alfatraining": "IU Akademie / WBS Training / alfatraining",
    "public funding bodies and employers": "Öffentliche Förderstellen und Arbeitgeber",
    "funded course place or employer training contract": "Geförderter Kursplatz oder betrieblicher Schulungsvertrag",
    "One marketplace for the whole car lifecycle. Private buyers and sellers use the core marketplace free with verified identity, escrow-ready workflows and guided pricing. Dealers, dealer groups and fleet sellers fund Zivvo through subscriptions covering multi-channel stock listings, trade sourcing, auction tools, valuation, finance and warranty connections, and lead management. Zivvo does not also charge private users a premium listing or platform transaction fee.": "Ein Marktplatz für den gesamten Fahrzeuglebenszyklus. Private Käufer und Verkäufer nutzen den Kernmarktplatz kostenlos mit verifizierter Identität, Treuhand-Workflows und Preisführung. Händler, Händlergruppen und Flottenverkäufer finanzieren Zivvo über Abonnements, die Multi-Channel-Bestandslistungen, Handelseinkauf, Auktionstools, Bewertung, Finanzierungs- und Garantieanbindungen sowie Lead-Management abdecken. Zivvo erhebt von Privatnutzern keine zusätzlichen Premium-Listing- oder Plattform-Transaktionsgebühren.",
    "Private buyers and sellers use the core marketplace free": "Private Käufer und Verkäufer nutzen den Kernmarktplatz kostenlos",
    "mobile.de": "mobile.de",
    "AutoScout24": "AutoScout24",
    "Kleinanzeigen (eBay)": "Kleinanzeigen (eBay)",
    "Auto1 / wirkaufendeinauto.de": "Auto1 / wirkaufendeinauto.de",
    "car dealers, dealer groups, fleets and trade sellers": "Autohändler, Händlergruppen, Flotten und gewerbliche Verkäufer",
    "dealer subscription by stock and location": "Händler-Abonnement nach Bestand und Standort",
    "Omniqora One — the complete AI business operating system: one login, one data core, one bill across every module": "Omniqora One — das komplette KI-Betriebssystem für Unternehmen: ein Login, ein Datenkern, eine Abrechnung über alle Module hinweg",
    "Qora — the central AI assistant that sits across the whole platform and answers, drafts, summarises and acts": "Qora — der zentrale KI-Assistent, der über die gesamte Plattform hinweg agiert und antwortet, entwirft, zusammenfasst sowie handelt",
    "Omniqora Connect — every conversation, one intelligent core: WhatsApp, Instagram, Messenger, SMS, e-mail, web-chat and Telegram in one team inbox": "Omniqora Connect — jede Konversation, ein intelligenter Kern: WhatsApp, Instagram, Messenger, SMS, E-Mail, Web-Chat und Telegram in einem Team-Posteingang",
    "Omniqora Voice — every call, intelligently handled: AI receptionist, call routing, callbacks, number porting and 24/7 out-of-hours cover": "Omniqora Voice — jeder Anruf, intelligent bearbeitet: KI-Empfang, Anruf-Routing, Rückrufe, Rufnummernportierung und 24/7-Abdeckung außerhalb der Geschäftszeiten",
    "Omniqora Flow — put your business in motion: workflow automation from intake to quote, scheduling, fulfilment and follow-up": "Omniqora Flow — bringen Sie Ihr Unternehmen in Bewegung: Workflow-Automatisierung von der Anfrage bis zum Angebot, Terminplanung, Erfüllung und Nachverfolgung",
    "Omniqora Agents — your AI team, ready to work: task-scoped AI employees for reception, sales follow-up, admin, billing chase and reporting": "Omniqora Agents — Ihr KI-Team, einsatzbereit: Aufgabenspezifische KI-Mitarbeiter für Empfang, Sales-Follow-up, Administration, Forderungsmanagement und Reporting",
    "Omniqora Exchange — connect more, achieve more: integration marketplace for calendars, CRM, accounting, payments and channel apps": "Omniqora Exchange — mehr vernetzen, mehr erreichen: Integrations-Marktplatz für Kalender, CRM, Buchhaltung, Zahlungen und Channel-Apps",
    "Brand structure: master brand Omniqora → platform Omniqora One → assistant Qora → AI employees Omniqora Agents → communications Omniqora Connect → AI receptionist Omniqora Voice → automation Omniqora Flow → marketplace Omniqora Exchange": "Markenstruktur: Dachmarke Omniqora → Plattform Omniqora One → Assistent Qora → KI-Mitarbeiter Omniqora Agents → Kommunikation Omniqora Connect → KI-Empfang Omniqora Voice → Automatisierung Omniqora Flow → Marktplatz Omniqora Exchange",
    "Their customers are never charged by Omniqora": "Deren Kunden werden niemals von Omniqora zur Kasse gebeten",
    "omniqora.com — the complete AI business operating system: one account, one data core, one bill across every module": "omniqora.com — das komplette KI-Betriebssystem für Unternehmen: ein Account, ein Datenkern, eine Abrechnung über alle Module hinweg",
    "Every conversation. One intelligent core — omnichannel team inbox with cases, SLAs and templates": "Jede Konversation. Ein intelligenter Kern — Omnichannel-Team-Posteingang mit Tickets, SLAs und Vorlagen",
    "Every call, intelligently handled — AI receptionist, routing, callbacks and 24/7 cover": "Jeder Anruf, intelligent bearbeitet — KI-Empfang, Routing, Rückrufe und 24/7-Abdeckung",
    "Put your business in motion — workflow automation from intake to quote, booking, fulfilment and follow-up": "Bringen Sie Ihr Unternehmen in Bewegung — Workflow-Automatisierung von der Anfrage bis zum Angebot, Buchung, Erfüllung und Nachverfolgung",
    "Your AI team, ready to work — task-scoped AI employees for reception, sales, admin and billing": "Ihr KI-Team, einsatzbereit — aufgabenspezifische KI-Mitarbeiter für Empfang, Vertrieb, Administration und Abrechnung",
    "Connect more. Achieve more — integration marketplace for calendars, CRM, accounting, payments and channels": "Mehr vernetzen. Mehr erreichen — Integrations-Marktplatz für Kalender, CRM, Buchhaltung, Zahlungen und Kanäle",
    "The central AI assistant across the platform: asks, drafts, summarises and acts inside every module": "Der zentrale KI-Assistent über die gesamte Plattform hinweg: Fragt, entwirft, fasst zusammen und handelt innerhalb jedes Moduls",
    "Customer": "Kunde",
    "Partner / agency / reseller": "Partner / Agentur / Reseller",
    "Intercom / Zendesk": "Intercom / Zendesk",
    "Superchat (DE)": "Superchat (DE)",
    "Respond.io / Trengo": "Respond.io / Trengo",
    "MessageBird / Bird, Twilio": "MessageBird / Bird, Twilio",
    "Front / HubSpot Service Hub": "Front / HubSpot Service Hub",
    "AI receptionist point tools (e.g. answering services)": "Spezialisierte KI-Empfangstools (z. B. Telefonservices)",
    "businesses, agencies, groups and resellers using the software": "Unternehmen, Agenturen, Gruppen und Reseller, die die Software nutzen",
    "business subscription by team, modules and usage": "Unternehmens-Abonnement nach Team, Modulen und Nutzung",
    "Universities and service partners are not charged a second platform fee": "Universitäten und Servicepartner zahlen keine zweite Plattformgebühr",
    "IDP / British Council counselling": "IDP / British Council Beratung",
    "Local Pakistani agents (SI-UK, Times Consultant)": "Lokale pakistanische Agenten (SI-UK, Times Consultant)",
    "DAAD / self-service": "DAAD / Self-Service",
    "students and their families buying the admissions and visa-support package": "Studierende und deren Familien, die das Zulassungs- und Visum-Supportpaket erwerben",
    "fixed, transparent student service package": "Festes, transparentes Servicepaket für Studierende",
    "Paying student cases": "Zahlende Studierendenfälle",
    "Average revenue per paying user / month": "Durchschnittlicher Umsatz pro zahlendem Nutzer / Monat",
    "Paying users cancelling each month": "Zahlende Nutzer, die monatlich kündigen",
    "Verified listings with HPI, MOT & mileage checks": "Verifizierte Inserate mit HPI-, TÜV- und Kilometerstands-Prüfungen",
    "Dealer stock feed import (AutoTrader/eBay/CSV)": "Händler-Bestands-Import (AutoTrader/eBay/CSV)",
    "Escrow payments with buyer protection": "Treuhandzahlungen mit Käuferschutz",
    "Finance & warranty quotes at checkout": "Angebote für Finanzierung & Garantie beim Checkout",
    "Nationwide delivery & collection booking": "Buchung von bundesweiter Lieferung & Abholung",
    "Part-exchange valuation tool": "Tool zur Inzahlungnahme-Bewertung",
    "In-app chat with fraud screening": "In-App-Chat mit Betrugs-Screening",
    "Dealer CRM with lead scoring": "Händler-CRM mit Lead-Scoring",
    "Photo AI: auto-enhance & background removal": "Foto-KI: Automatische Optimierung & Hintergrundentfernung",
    "Reviews & verified-seller badges": "Bewertungen & Verifizierter-Verkäufer-Badges",
    "Public search, listings, checkout": "Öffentliche Suche, Inserate, Checkout",
    "Stock, leads, pricing, analytics": "Bestand, Leads, Preisgestaltung, Analysen",
    "Buyer search & alerts": "Käufersuche & Benachrichtigungen",
    "Stock feed ingest & syndication": "Bestands-Import & Syndizierung",
    "Independent dealer": "Unabhängiger Händler",
    "Lists 40 cars, pays one flat fee instead of per-advert pricing.": "Listet 40 Autos, zahlt eine Pauschalgebühr statt Preis pro Anzeige.",
    "Sells with verified checks and escrow protection.": "Verkauft mit verifizierten Prüfungen und Treuhandschutz.",
    "Buyer": "Käufer",
    "Filters by verified history, books delivery.": "Filtert nach verifizierter Historie, bucht Lieferung.",
    "Finance broker": "Finanzierungsmakler",
    "Receives qualified, pre-checked applications.": "Erhält qualifizierte, vorab geprüfte Anträge.",
    "Auto Trader price war": "Preiskrieg mit Auto Trader",
    "Our unit economics rely on transaction and finance commissions, not listing rent, so we can undercut indefinitely.": "Unsere Unit Economics basieren auf Transaktions- und Finanzierungsprovisionen, nicht auf Einstellgebühren, sodass wir dauerhaft günstiger sein können.",
    "Fraudulent listings": "Betrügerische Inserate",
    "Mandatory V5C/HPI verification, ID checks and escrow-only payments on private sales.": "Verpflichtende Dokumenten-Verifizierung, ID-Checks und ausschließliche Treuhandzahlungen bei Privatverkäufen.",
    "Auto Trader": "Auto Trader",
    "Dominant audience and dealer habit": "Dominante Reichweite und Händlergewohnheiten",
    "Motors.co.uk / eBay Motors": "Motors.co.uk / eBay Motors",
    "Cheap listing volume": "Günstiges Inseratsvolumen",
    "Verification-first trust layer and integrated payments; we monetise transactions, not clicks, so listings can be near-free": "Vertrauensschicht durch Vorab-Verifizierung und integrierte Zahlungen; wir monetarisieren Transaktionen statt Klicks, wodurch Inserate nahezu kostenlos sein können",
    "UK car dealers, dealer groups and fleet sellers": "Britische Autohändler, Händlergruppen und Flottenverkäufer",
    "dealer subscription by stock and forecourt": "Händler-Abonnement nach Bestand und Standort",
    "Postcode & availability search with filters": "Postleitzahl- & Verfügbarkeitssuche mit Filtern",
    "Agency registration and Ofsted-equivalent oversight": "Agentur-Registrierung und Aufsicht (analog zu Ofsted)",
    "DBS, first-aid and insurance expiry tracking": "Überwachung der Gültigkeit von Führungszeugnis, Erste-Hilfe-Kurs und Versicherung",
    "EYFS learning journals with photo observations": "EYFS-Lerntagebücher mit Fotobeobachtungen",
    "Automated invoicing, Tax-Free Childcare & funded hours": "Automatisierte Rechnungsstellung, steuerfreie Kinderbetreuung & Förderstunden",
    "Daily registers and ratio checks": "Tägliche Anwesenheitslisten und Personalschlüssel-Prüfungen",
    "Parent app with daily diary and messaging": "Eltern-App mit Tagebuch und Nachrichtenfunktion",
    "Employer benefit portal": "Mitarbeitervorteils-Portal",
    "Review and verification badges": "Bewertungs- und Verifizierungs-Badges",
    "Vacancy alerts for parents": "Benachrichtigungen über freie Plätze für Eltern",
    "Parents search and organise childcare without a platform fee": "Eltern suchen und organisieren Kinderbetreuung ohne Plattformgebühr",
    "Parent search and booking": "Elternsuche und -buchung",
    "Registers, journals, invoicing": "Listen, Tagebücher, Rechnungsstellung",
    "Daily diary, payments, messaging": "Tagebuch, Zahlungen, Nachrichten",
    "Vetting, inspection, compliance": "Prüfung, Inspektion, Compliance",
    "Finds and books a vetted childminder near work or home.": "Findet und bucht eine geprüfte Kindertagespflegeperson in der Nähe von Arbeit oder Zuhause.",
    "Childminder": "Kindertagespflegeperson",
    "Employer": "Arbeitgeber",
    "Offers a vetted childcare benefit to staff.": "Bietet Mitarbeitern geprüfte Kinderbetreuung als Benefit an.",
    "Agency inspector": "Agentur-Inspektor",
    "Runs quality visits and records outcomes.": "Führt Qualitätsbesuche durch und dokumentiert die Ergebnisse.",
    "Parents use Childcare.co.uk classifieds, Facebook groups and word of mouth; providers juggle paper registers, Excel invoices and separate learning-journal apps (Tapestry, Famly). Agencies (tiney, Koru Kids) cover only a fraction of the country.": "Eltern nutzen Childcare.co.uk-Kleinanzeigen, Facebook-Gruppen und Mundpropaganda; Anbieter hantieren mit Papierlisten, Excel-Rechnungen und separaten Lerntagebuch-Apps (Tapestry, Famly). Agenturen (tiney, Koru Kids) decken nur einen Bruchteil des Landes ab.",
    "Ofsted / DfE agency rule change": "Änderung der Agentur-Regeln durch Ofsted / DfE",
    "Dual model: even without agency status the directory + software business stands alone.": "Duales Modell: Auch ohne Agenturstatus ist das Verzeichnis- + Softwaregeschäft eigenständig tragfähig."
}

# Check if all keys from input are present
for item in data:
    if item not in translations:
        print(f"MISSING: {item}")

with open('/tmp/de0.json', 'w', encoding='utf-8') as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)
