/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsBrandIdRouteImport } from './routes/brands.$brandId'
import { Route as ApiPublicUnlockRouteImport } from './routes/api/public/unlock'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUnlockRoute = ApiPublicUnlockRouteImport.update({
  id: '/api/public/unlock',
  path: '/api/public/unlock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/api/public/unlock': typeof ApiPublicUnlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/api/public/unlock': typeof ApiPublicUnlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/api/public/unlock': typeof ApiPublicUnlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/unlock' | '/brands/$brandId' | '/api/public/unlock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/unlock' | '/brands/$brandId' | '/api/public/unlock'
  id: '__root__' | '/' | '/unlock' | '/brands/$brandId' | '/api/public/unlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnlockRoute: typeof UnlockRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  ApiPublicUnlockRoute: typeof ApiPublicUnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unlock': {
      id: '/api/public/unlock'
      path: '/api/public/unlock'
      fullPath: '/api/public/unlock'
      preLoaderRoute: typeof ApiPublicUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnlockRoute: UnlockRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  ApiPublicUnlockRoute: ApiPublicUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
